export const SearchSuggestionData = [
  {
    category: "Trending",
    data: [
      "Gujraj elections",
      "Cricket",
      "Stock markrt",
      "Latest news",
      "MS dhoni",
    ],
  },
  {
    category: "Most Searches",
    data: [
      "Breaking News",
      "Top Stories",
      "Latest Updates",
      "Current Events",
      "News Alert",
    ],
  },
];

export const languagesData = [
  {
    id: "1",
    lang: "অসমীয়া",
    // "url": "https://as.vikaspedia.in/agriculture",
    url: "https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl",
    color: "#dddddd",
    logo: "অ",
    lgn_id: 4,
    lgn_code: "as",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "কৃষি",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ই-গভৰ্নেন্স",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "শিক্ষা",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "শক্তি",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "স্বাস্থ্য",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "সমাজ কল্যাণ",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/social-welfare`,
        value: "social-welfare",
      },
    ],
    // 'lgn_code':
  },
  {
    id: "2",
    lang: "বাংলা",
    // "url": 'https://bn.vikaspedia.in/',
    url: "https://xn--p5by0ags3b6blfceb.xn--45brj9c/",
    color: "#ffe6e6",
    logo: "আ",
    lgn_id: 5,
    lgn_code: "bn",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "কৃষি",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ই-গভর্ন্যান্স",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "শিক্ষা",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "শক্তি",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "স্বাস্থ্য",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "সমাজ কল্যাণ",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "3",
    lang: "बोडो",
    // "url": 'https://brx.vikaspedia.in/agriculture',
    url: "https://xn--11b8algs5c0becf0g.xn--h2brj9c",
    color: "#fefab3",
    logo: "अ",
    lgn_id: 6,
    lgn_code: "brx",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "Agriculture",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "e-Governance",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "Education",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "Energy",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "Health",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "Social Welfare",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "4",
    lang: "डोगरी",
    // "url": 'https://doi.vikaspedia.in/agriculture',
    url: "https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c",
    color: "#dde9b3",
    logo: "अ",
    lgn_id: 7,
    lgn_code: "doi",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "खेतीबाड़ी",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ई-गवर्नेंस",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "शिक्षा",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ऊर्जा",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "सेहत",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "समाज कल्याण",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "5",
    lang: "English",
    url: "https://vikaspedia.in/InDG",
    color: "#E0FFFF",
    logo: "A",
    lgn_id: 1,
    lgn_code: "en",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "Agriculture",
        url: `https://vikaspedia.in/agriculture`,
        value: "agriculture",
      },
      {
        hoverText: "Aspirational District",
        icon: "location-pin",
        label: "Aspirational District",
        url: `https://vikaspedia.in/aspirational`,
        value: "aspirational",
      },
      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "e-Governance",
        url: `https://vikaspedia.in/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "Education",
        url: `https://vikaspedia.in/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "Energy",
        url: `https://vikaspedia.in/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "Health",
        url: `https://vikaspedia.in/health`,
        value: "health",
      },
      {
        hoverText: "Schemes",
        icon: "list-alt",
        label: "Schemes",
        url: `https://vikaspedia.in/schemes`,
        value: "schemes",
      },
      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "Social Welfare",
        url: `https://vikaspedia.in/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "6",
    lang: "ગુજરાતી",
    // "url": 'https://gu.vikaspedia.in/agriculture',
    url: "https://xn--0dcy0av0at5becfj.xn--gecrj9c/",
    color: "#bfe6db",
    logo: "અ",
    lgn_id: 8,
    lgn_code: "gu",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "કૃષિ",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ઇ-ગવર્નન્સ",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/e-governance`,
        value: "ઇ-ગવર્નન્સ",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "શિક્ષણ",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ઊર્જા",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "આરોગ્ય",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "સમાજ કલ્યાણ",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "7",
    lang: "हिन्दी",
    // "url": "https://hi.vikaspedia.in/",
    url: "https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/",
    color: "#f6e1d2",
    logo: "अ",
    lgn_id: 2,
    lgn_code: "hi",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "कृषि",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },
      {
        hoverText: "Aspirational District",
        icon: "location-pin",
        label: "आकांक्षात्मक जिला",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/aspirational`,
        value: "aspirational",
      },
      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ई-गवर्नेंस",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "शिक्षा",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ऊर्जा",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "स्वास्थ्य",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },
      {
        hoverText: "Schemes",
        icon: "list-alt",
        label: "योजनाओं",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/schemes`,
        value: "schemes",
      },
      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "सामाजिक कल्याण",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "8",
    lang: "ಕನ್ನಡ",
    // "url": 'https://kn.vikaspedia.in/agriculture',
    url: "https://xn--nscy0av0at5bgfi5l.xn--2scrj9c",
    color: "#dec7de",
    logo: "ಅ",
    lgn_id: 10,
    lgn_code: "kn",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "ಕೃಷಿ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ಇ-ಆಡಳಿತ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "ಶಿಕ್ಷಣ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ಶಕ್ತಿ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "ಆರೋಗ್ಯ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "ಸಮಾಜ ಕಲ್ಯಾಣ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "9",
    lang: "كأشُر",
    url: "https://ks.vikaspedia.in/agriculture",
    color: "#f5c1d0",
    logo: "𑆕",
    lgn_id: 11,
    lgn_code: "csb",
  },
  {
    id: "10",
    lang: "कोंकणी",
    // "url": 'https://kok.vikaspedia.in/agriculture',
    url: "https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c",
    color: "#fedbcc",
    logo: "अ",
    lgn_id: 12,
    lgn_code: "kok",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "शेती",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ई-गव्हर्नन्स",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "शिक्षण",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "उर्जा",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "भलायकी",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "समाज कल्याण",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "11",
    lang: "मैथिली",
    // "url": 'https://mai.vikaspedia.in/agriculture',
    url: "https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c",
    color: "#ffc2f0",
    logo: "अ",
    lgn_id: 13,
    lgn_code: "mai",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "खेती",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ई-शासन",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "शिक्षा",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "उर्जा",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "स्वास्थ्य",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "समाज कल्याण",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "12",
    lang: "മലയാളം",
    // "url": 'https://ml.vikaspedia.in/',
    url: "https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/",
    color: "#f0d3bc",
    logo: "ക",
    lgn_id: 14,
    lgn_code: "ml",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "കൃഷി",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ഇ-ഭരണനിർവ്വഹണം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "വിദ്യാഭ്യാസം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ഊർജ്ജം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "ആരോഗ്യം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "സാമൂഹ്യക്ഷേമം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "13",
    lang: "মনিপুরি",
    // "url": 'https://mni.vikaspedia.in/agriculture',
    url: "https://xn--p5b8algs5c5alfceb.xn--45brj9c",
    color: "#dae7e1",
    logo: "ꯑ",
    lgn_id: 15,
    lgn_code: "mni",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "Agriculture",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "e-Governance",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "Education",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "Energy",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "Health",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "Social Welfare",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "14",
    lang: "मराठी",
    // "url": 'https://mr.vikaspedia.in/',
    url: "https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/",
    color: "#ccd7e1",
    logo: "अ",
    lgn_id: 3,
    lgn_code: "mr",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "शेती",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ई-गव्हर्नन्स",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "शिक्षण",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ऊर्जा",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "आरोग्य",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "सामाजिक कल्याण",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "15",
    lang: "नेपाली",
    // "url": 'https://ne.vikaspedia.in/agriculture',
    url: "https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c",
    color: "#cccecb",
    logo: "अ",
    lgn_id: 9,
    lgn_code: "ne",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "कृषि",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ई-शासन",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "शिक्षा",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ऊर्जा",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "स्वास्थ्य",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "सामाजिक कल्याण",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "16",
    lang: "ଓଡିଆ",
    // "url": 'https://or.vikaspedia.in/agriculture',
    url: "https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c",
    color: "#E0FFFF",
    logo: "ଆ",
    lgn_id: 16,
    lgn_code: "or",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "କୃଷି",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ଇ-ଶାସନ",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "ଶିକ୍ଷା",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ଶକ୍ତି",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "ସ୍ୱାସ୍ଥ୍ୟ",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "ସାମାଜିକ କଲ୍ୟାଣ",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "17",
    lang: "ਪੰਜਾਬੀ",
    // "url": 'https://pa.vikaspedia.in/agriculture',
    url: "https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c",
    color: "#dde9b3",
    logo: "ਅ",
    lgn_id: 17,
    lgn_code: "pa",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "ਖੇਤੀਬਾੜੀ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ਈ-ਗਵਰਨੈਂਸ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "ਸਿੱਖਿਆ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ਊਰਜਾ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "ਸਿਹਤ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "ਸਮਾਜਿਕ ਭਲਾਈ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "18",
    lang: "संस्कृतम्",
    // "url": 'https://sa.vikaspedia.in/agriculture',
    url: "https://xn--11by0av0at5becfj.xn--h2breg3eve",
    color: "#f6e1d2",
    logo: "अ",
    lgn_id: 18,
    lgn_code: "sa",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "कृषि",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ई-शासनम्",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "शिक्षा",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "ऊर्जाम्",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "स्वास्थ्यम्",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "समाज कल्याण",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "19",
    lang: "ᱥᱟᱱᱛᱟᱞᱤ",
    // "url": 'https://sat.vikaspedia.in/agriculture',
    url: "https://xn--11by0av0at5becfj.xn--h2brj9c8c",
    color: "#cccecb",
    logo: "ᱚ",
    lgn_id: 19,
    lgn_code: "sat",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "Agriculture",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "e-Governance",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "Education",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "Energy",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "Health",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "Social Welfare",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "20",
    lang: "सिंधी",
    // "url": 'https://sd.vikaspedia.in/agriculture',
    url: "https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c",
    color: "#ccd7e1",
    logo: "अ",
    lgn_id: 20,
    lgn_code: "sd",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "ज़राअत",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ए गवर्नन्स",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "तालीम",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "शक्ती",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "सिहत",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "समाजी भलाई",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "21",
    lang: "தமிழ்",
    // "url": 'https://ta.vikaspedia.in/',
    url: "https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/",
    color: "#dec7de",
    logo: "அ",
    lgn_id: 21,
    lgn_code: "ta",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "வேளாண்மை",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "மின்னாட்சி",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "கல்வி",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "எரிசக்தி",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "ஆரோக்கியம்",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "சமூக நலம்",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "22",
    lang: "తెలుగు",
    // "url": 'https://te.vikaspedia.in/', https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/
    url: "https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/",
    color: "#85B09A",
    logo: "అ",
    lgn_id: 22,
    lgn_code: "te",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "వ్యవసాయం",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ఇ-పాలన",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "విద్య",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "శక్తి",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "ఆరోగ్యం",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "సామాజిక సంక్షేమం",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
  {
    id: "23",
    lang: "اردو",
    // "url": 'https://ur.vikaspedia.in/agriculture',
    url: "https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e",
    color: "#dddddd",
    logo: "اَ",
    lgn_id: 23,
    lgn_code: "ur",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: "grass",
        label: "زراعت",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: "landmark",
        label: "ای گورننس",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/e-governance`,
        value: "e-Governance",
      },
      {
        hoverText: "Education",
        icon: "school",
        label: "تعلیم",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: "energy-savings-leaf",
        label: "توانائی",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: "health-and-safety",
        label: "صحت",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: "diversity-1",
        label: "سماجی بہبود",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/social-welfare`,
        value: "social-welfare",
      },
    ],
  },
];

export const sectors = [
  {
    id: 1,
    hoverText: "Agriculture",
    icon: "grass",
    label: "Agriculture",
    url: `https://vikaspedia.in/agriculture`,
    value: "agriculture",
  },
  {
    id: 2,
    hoverText: "Aspirational District",
    icon: "location-pin",
    label: "Aspirational District",
    url: `https://vikaspedia.in/aspirational`,
    value: "aspirational",
  },
  {
    id: 3,
    hoverText: "e-Governance",
    icon: "landmark",
    label: "e-Governance",
    url: `https://vikaspedia.in/e-governance`,
    value: "e-governance",
  },
  {
    id: 4,
    hoverText: "Education",
    icon: "school",
    label: "Education",
    url: `https://vikaspedia.in/education`,
    value: "education",
  },
  {
    id: 5,
    hoverText: "Energy",
    icon: "energy-savings-leaf",
    label: "Energy",
    url: `https://vikaspedia.in/energy`,
    value: "energy",
  },
  {
    id: 6,
    hoverText: "Health",
    icon: "health-and-safety",
    label: "Health",
    url: `https://vikaspedia.in/health`,
    value: "health",
  },
  {
    id: 7,
    hoverText: "Schemes",
    icon: "list-alt",
    label: "Schemes",
    url: `https://vikaspedia.in/schemes`,
    value: "schemes",
  },
  {
    id: 8,
    hoverText: "Social Welfare",
    icon: "diversity-1",
    label: "Social Welfare",
    url: `https://vikaspedia.in/social-welfare`,
    value: "social-welfare",
  },
];
