import AssuredWorkloadIcon from "@mui/icons-material/AssuredWorkload";
import Diversity3Icon from "@mui/icons-material/Diversity3";
import LocationCityIcon from "@mui/icons-material/LocationCity";
import ListAltIcon from "@mui/icons-material/ListAlt";
import SchoolIcon from "@mui/icons-material/School";
import WindPowerIcon from "@mui/icons-material/WindPower";

import AgricultureIcon from "@mui/icons-material/Grass";
import HealthAndSafetyIcon from "@mui/icons-material/LocalHospital";

const CdacIcon = "./officialslogo/cdac/75x75.png";
const DigitalIndiaIcon = "./officialslogo/digitalindia/200x70.png";
const MeityIcon = "./officialslogo/meity/200x75.png";

const AppStoreIcon = "./appstore/appstore/200x75.png";
const PlayStoreIcon = "./appstore/playstore/200x75.png";

const FacebookIcon = "./socialmedia2/fb/75x75.png";
const InstagramIcon = "./socialmedia2/ig/75x75.png";
const LinkedInIcon = "./socialmedia2/li/75x75.png";
const TwitterIcon = "./socialmedia2/tt/75x75.png";
const YouTubeIcon = "./socialmedia2/yt/youtube_social_squircle_red.png";

export const BASE_URL = "bb";
export const BASE_URL_SEARCH = "https://dashboard.vikaspedia.in/";
export const KEY_ACCESS_TOKEN = "s_t_l";

export const languages = [
  {
    label: "অসমীয়া",
    value: "as",
    url: "https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/",
    hoverText: "Assamese",
  },
  {
    label: "বাংলা",
    value: "bn",
    url: "https://xn--p5by0ags3b6blfceb.xn--45brj9c/",
    hoverText: "Bengali",
  },
  {
    label: "बोडो",
    value: "brx",
    url: "https://xn--11b8algs5c0becf0g.xn--h2brj9c/",
    hoverText: "Bodo",
  },
  {
    label: "डोंगरी",
    value: "doi",
    url: "https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Dongri",
  },
  {
    label: "English",
    value: "en",
    url: "https://vikaspedia.in/InDG/",
    hoverText: "English",
  },
  {
    label: "ગુજરાતી",
    value: "gu",
    url: "https://xn--0dcy0av0at5becfj.xn--gecrj9c/",
    hoverText: "Gujarati",
  },
  {
    label: "हिन्दी",
    value: "hi",
    url: "https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Hindi",
  },
  {
    label: "ಕನ್ನಡ",
    value: "kn",
    url: "https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/",
    hoverText: "Kannada",
  },
  {
    label: "كٲشُر",
    value: "ks",
    url: "https://ks.vikaspedia.in/",
    hoverText: "Kashmiri",
  },
  {
    label: "कोंकणी",
    value: "kok",
    url: "https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Konkani",
  },
  {
    label: "मैथिली",
    value: "mai",
    url: "https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Maithili",
  },
  {
    label: "മലയാളം",
    value: "ml",
    url: "https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/",
    hoverText: "Malayalam",
  },
  {
    label: "মণিপুরি",
    value: "mni",
    url: "https://xn--p5b8algs5c5alfceb.xn--45brj9c/",
    hoverText: "Manipuri",
  },
  {
    label: "मराठी",
    value: "mr",
    url: "https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Marathi",
  },
  {
    label: "नेपाली",
    value: "ne",
    url: "https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Nepali",
  },
  {
    label: "ଓଡିଆ",
    value: "or",
    url: "https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/",
    hoverText: "Odia",
  },
  {
    label: "ਪੰਜਾਬੀ",
    value: "pa",
    url: "https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/",
    hoverText: "Punjabi",
  },
  {
    label: "संस्कृत",
    value: "sa",
    url: "https://xn--11by0av0at5becfj.xn--h2breg3eve/",
    hoverText: "Sanskrit",
  },
  {
    label: "ᱥᱟᱱᱛᱟᱲᱤ",
    value: "sat",
    url: "https://xn--11by0av0at5becfj.xn--h2brj9c8c/",
    hoverText: "Santali",
  },
  {
    label: "सिंधी",
    value: "sd",
    url: "https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Sindhi",
  },
  {
    label: "தமிழ்",
    value: "ta",
    url: "https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/",
    hoverText: "Tamil",
  },
  {
    label: "తెలుగు",
    value: "te",
    url: "https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/",
    hoverText: "Telugu",
  },
  {
    label: "اردو",
    value: "ur",
    url: "https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/",
    hoverText: "Urdu",
  },
];

export const mergedOptions = [
  {
    label: "Select Language",
    value: "0",
    urlOriginal: "https://vikaspedia.in/populer-topics/",
    urlNew: "https://vikaspedia.in/populer-topics/",
    hoverText: "Select Language",
    ShortName: "en",
  },
  {
    label: "অসমীয়া",
    value: "1",
    urlOriginal: "https://as.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/",
    hoverText: "Assamese",
    ShortName: "as",
  },
  {
    label: "বাংলা",
    value: "2",
    urlOriginal: "https://bn.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--p5by0ags3b6blfceb.xn--45brj9c/",
    hoverText: "Bengali",
    ShortName: "bn",
  },
  {
    label: "बोडो",
    value: "3",
    urlOriginal: "https://brx.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--11b8algs5c0becf0g.xn--h2brj9c/",
    hoverText: "Bodo",
    ShortName: "brx",
  },
  {
    label: "डोंगरी",
    value: "4",
    urlOriginal: "https://doi.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Dongri",
    ShortName: "doi",
  },
  {
    label: "English",
    value: "5",
    urlOriginal: "https://en.vikaspedia.in/populer-topics/",
    urlNew: "https://vikaspedia.in/",
    hoverText: "English",
    ShortName: "en",
  },
  {
    label: "ગુજરાતી",
    value: "6",
    urlOriginal: "https://gu.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--0dcy0av0at5becfj.xn--gecrj9c/",
    hoverText: "Gujarati",
    ShortName: "gu",
  },
  {
    label: "हिन्दी",
    value: "7",
    urlOriginal: "https://hi.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Hindi",
    ShortName: "hi",
  },
  {
    label: "ಕನ್ನಡ",
    value: "8",
    urlOriginal: "https://kn.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/",
    hoverText: "Kannada",
    ShortName: "kn",
  },
  {
    label: "كٲشُر",
    value: "9",
    urlOriginal: "https://ks.vikaspedia.in/populer-topics/",
    urlNew: "https://ks.vikaspedia.in/populer-topics/",
    urlNew2: "https://xn----ymcb0c2fvdtnxczo9lc.xn--mgbbh1a/",
    hoverText: "Kashmiri",
    ShortName: "ks",
  },
  {
    label: "कोंकणी",
    value: "10",
    urlOriginal: "https://kok.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "konkani",
    ShortName: "kok",
  },
  {
    label: "मैथिली",
    value: "11",
    urlOriginal: "https://mai.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Maithili",
    ShortName: "mai",
  },
  {
    label: "മലയാളം",
    value: "12",
    urlOriginal: "https://ml.vikaspedia.in/populer-topics/",
    urlNew: "https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/",
    hoverText: "Malayalam",
    ShortName: "ml",
  },
  {
    label: "মণিপুরি",
    value: "13",
    urlOriginal: "https://mni.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--p5b8algs5c5alfceb.xn--45brj9c/",
    hoverText: "manipuri",
    ShortName: "mni",
  },
  {
    label: "मराठी",
    value: "14",
    urlOriginal: "https://mr.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Marathi",
    ShortName: "mr",
  },
  {
    label: "नेपाली",
    value: "15",
    urlOriginal: "https://ne.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Nepali",
    ShortName: "ne",
  },
  {
    label: "ଓଡ଼ିଆ",
    value: "16",
    urlOriginal: "https://or.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/",
    hoverText: "Odia",
    ShortName: "or",
  },
  {
    label: "ਪੰਜਾਬੀ",
    value: "17",
    urlOriginal: "https://pa.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/",
    hoverText: "Punjabi",
    ShortName: "pa",
  },
  {
    label: "संस्कृत",
    value: "18",
    urlOriginal: "https://sa.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--11by0av0at5becfj.xn--h2breg3eve/",
    hoverText: "Sanskrit",
    ShortName: "sa",
  },
  {
    label: "ᱥᱟᱱᱛᱟᱲᱤ",
    value: "19",
    urlOriginal: "https://sat.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--11by0av0at5becfj.xn--h2brj9c8c/",
    hoverText: "Santali",
    ShortName: "sat",
  },
  {
    label: "सिंधी",
    value: "20",
    urlOriginal: "https://sd.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/",
    hoverText: "Sindhi",
    ShortName: "sd",
  },
  {
    label: "தமிழ்",
    value: "21",
    urlOriginal: "https://ta.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/",
    hoverText: "Tamil",
    ShortName: "ta",
  },
  {
    label: "తెలుగు",
    value: "22",
    urlOriginal: "https://te.vikaspedia.in/populer-topics/",
    urlNew: "https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/",
    hoverText: "Telugu",
    ShortName: "te",
  },
  {
    label: "اردو",
    value: "23",
    urlOriginal: "https://ur.vikaspedia.in/populer-topics/",
    urlNew: "https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/",
    hoverText: "Urdu",
    ShortName: "ur",
  },
];

export const vikaspediaNames = [
  "Vikaspedia",
  "বিকাশপেডিয়া",
  "विकासपीडिया",
  "વિકાસપીડિયા",
  "ವಿಕಾಸ್ಪೀಡಿಯ",
  "വികാസ്-പീഡിയ",
  "বিকাসপিদিয়া",
  "ବିକାଶପିଡ଼ିଆ",
  "বিকাশপিডিয়া",
  "ਵਿਕਾਸਪੀਡੀਆ",
  "விகாஸ்பீடியா",
  "వికాస్పీడియా",
  "وکاس-پیڈیا",
];

//unused hai abi
export const IDN_SITE_URL = {
  AS_URL: "https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl",
  BN_URL: "https://xn--p5by0ags3b6blfceb.xn--45brj9c",
  BRX_URL: "https://xn--11b8algs5c0becf0g.xn--h2brj9c",
  DOI_URL: "https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c",
  EN_URL: "https://vikaspedia.in",
  GU_URL: "https://xn--0dcy0av0at5becfj.xn--gecrj9c",
  HI_URL: "https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c",
  KN_URL: "https://xn--nscy0av0at5bgfi5l.xn--2scrj9c",
  KS_URL: "https://xn----ymcb0c2fvdtnxczo9lc.xn--mgbbh1a",
  KOK_URL: "https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c",
  MAI_URL: "https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c",
  ML_URL: "https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e",
  MNI_URL: "https://xn--p5b8algs5c5alfceb.xn--45brj9c",
  MR_URL: "https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c",
  NE_URL: "https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c",
  OR_URL: "https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c",
  PA_URL: "https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c",
  SA_URL: "https://xn--11by0av0at5becfj.xn--h2breg3eve",
  SD_URL: "https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c",
  TA_URL: "https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h",
  SAT_URL: "https://xn--11by0av0at5becfj.xn--h2brj9c8c",
  TE_URL: "https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d",
  UR_URL: "https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e",
};

export const placeholderText = {
  as: "সন্ধান কৰিবলৈ লিখনী সুমুৱাওক",
  bn: "অনুসন্ধানের জন্য পাঠ্য লিখুন",
  brx: "search (सार्स) खालामनो text (टेक्सट) हो।",
  doi: "खोज करने लेई पाठ दर्ज करो",
  en: "Enter text to search",
  gu: "શોધવા માટે ટેક્સ્ટ દાખલ કરો",
  hi: "खोजने के लिए पाठ दर्ज करें",
  kn: "ಹುಡುಕಲು ಪಠ್ಯವನ್ನು ನಮೂದಿಸಿ",
  kok: "सोदपाक मजकूर घाल",
  ks: "متن کْریو اینٹر تلاش کرنْہ باپت",
  mai: "खोजबाक लेल पाठ दिअ'",
  ml: "തിരയുന്നതിനായി ടെക്സ്റ്റ് നൽകുക",
  mni: "Enter text to search",
  mr: "शोधण्यासाठी मजकूर प्रविष्ट करा",
  ne: "खोजी गर्न पाठ प्रविष्ट गर्नुहोस्",
  or: "ସନ୍ଧାନ କରିବାକୁ ପାଠ ପ୍ରବେଶ କରନ୍ତୁ |",
  pa: "ਖੋਜ ਕਰਨ ਲਈ ਟੈਕਸਟ ਦਰਜ ਕਰੋ",
  sa: "अन्वेषणार्थं पाठं प्रविशतु",
  sat: "Enter text to search",
  sd: "ڳولهڻ لاءِ متن داخل ڪريو",
  ta: "தேட வார்த்தையை உள்ளிடவும்",
  te: "శోధన కోసం వచనాన్ని నమోదు చేయండి",
  ur: "تلاش کرنے کے لیے متن درج کریں۔",
};

export const landingPageText = [
  {
    languageShortName: "en",
    aboutPortal1Text:
      "Vikaspedia is a nationwide multilingual knowledge-sharing platform that provides digital resources for societal development.",
    aboutPortal2Text: "Government of India initiative executed by the",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "Vikaspedia iOS App (External link)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (External link)",
    cdacText: "Centre for Development of Advanced Computing (C-DAC).",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "Digital India (External link)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "Vikaspedia Facebook (External link)",
    hoverText: "English",
    instagramIcon: InstagramIcon,
    instagramLogoText: "Vikaspedia Instagram (External link)",
    label: "Select language",
    lastmodified: "Last Modified",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "Vikaspedia LinkedIn (External link)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (External link)",
    meityText: "Ministry of Electronics and Information Technology (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "Vikaspedia Android App (External link)",
    searchButton: "Click here to search",
    searchErrorText: "Special characters are not allowed",
    searchPlaceholderText: "Enter text to search",
    searchText: "Search",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "Agriculture",
        url: `https://vikaspedia.in/agriculture`,
        value: "agriculture",
      },
      {
        hoverText: "Aspirational District",
        icon: LocationCityIcon,
        label: "Aspirational District",
        url: `https://vikaspedia.in/aspirational`,
        value: "aspirational",
      },
      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "e-Governance",
        url: `https://vikaspedia.in/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "Education",
        url: `https://vikaspedia.in/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "Energy",
        url: `https://vikaspedia.in/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "Health",
        url: `https://vikaspedia.in/health`,
        value: "health",
      },
      {
        hoverText: "Schemes",
        icon: ListAltIcon,
        label: "Schemes",
        url: `https://vikaspedia.in/schemes`,
        value: "schemes",
      },
      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "Social Welfare",
        url: `https://vikaspedia.in/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "Sectors",
    selectLanguageText: "Select language",
    twitterIcon: TwitterIcon,
    twitterLogoText: "Vikaspedia X (External link)",
    urlAlternative: "",
    urlIdn: "https://vikaspedia.in/InDG",
    urlLocal: "",
    urlSearch: "https://vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "0",
    vikaspediaLogoText: "Vikaspedia",
    vikaspediaOfferedIn: "Vikaspedia offered in",
    whatsappIcon: "",
    whatsappLogoText: "Vikaspedia WhatsApp (External link)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "Vikaspedia YouTube (External link)",
  },
  {
    languageShortName: "as",
    aboutPortal1Text:
      "বিকাশপিডিয়া হৈছে দেশজোৰা বহুভাষিক জ্ঞান বিনিময়ৰ মঞ্চ যিয়ে সমাজৰ উন্নয়নৰ বাবে ডিজিটেল সম্পদ প্ৰদান কৰে।",
    aboutPortal2Text: " ই ভাৰত চৰকাৰৰ এক পদক্ষেপ যিটো",
    aboutPortal3Text: "দ্বাৰা ৰূপায়িত।",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "বিকাশপিডিয়া iOS এপ (বাহ্যিক লিংক)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (বাহ্যিক লিংক)",
    cdacText: "চেণ্টাৰ ফৰ ডেভেলপমেণ্ট অৱ এডভান্সড কম্পিউটিং (C-DAC)ৰ",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "ডিজিটেল ভাৰত (বাহ্যিক লিংক)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "বিকাশপিডিয়া ফেচবুক (বাহ্যিক লিংক)",
    hoverText: "Assamese",
    instagramIcon: InstagramIcon,
    instagramLogoText: "বিকাশপেডিয়া ইনষ্টাগ্ৰাম (বাহ্যিক লিংক)",
    label: "অসমীয়া",
    lastmodified: "নবীনতম্ সংশোধন",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "বিকাশপিডিয়া লিংক্ডইন(বাহ্যিক লিংক)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (বাহ্যিক লিংক)",
    meityText: "ইলেক্ট্ৰনিকছ আৰু তথ্য প্ৰযুক্তি মন্ত্ৰালয়ৰ (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "বিকাশপিডিয়া এণ্ড্ৰইড এপ (বাহ্যিক লিংক)",
    searchButton: "ইয়াত ক্লিক কৰক সন্ধান কৰিবলৈ",
    searchErrorText: "বিশেষ আখৰৰ অনুমতি দিয়া হোৱা নাই",
    searchPlaceholderText: "সন্ধান কৰিবলৈ লিখনী সুমুৱাওক",
    searchText: "সন্ধান",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "কৃষি",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ই-গভৰ্নেন্স",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "শিক্ষা",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "শক্তি",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "স্বাস্থ্য",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "সমাজ কল্যাণ",
        url: `https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "ছেক্টৰসমূহ",
    selectLanguageText: "ভাষা নিৰ্বাচন কৰক",
    twitterIcon: TwitterIcon,
    twitterLogoText: "বিকাশপিডিয়া টুইটাৰ (বাহ্যিক লিংক)",
    urlAlternative: "",
    urlIdn: "https://xn--p5by0ags3b6blfcf8g.xn--45br5cyl",
    urlLocal: "",
    urlSearch: "https://as.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "1",
    vikaspediaLogoText: "বিকাশপেডিয়া",
    vikaspediaOfferedIn: "বিকাশপিডিয়াত আগবঢ়োৱা হৈছে",
    whatsappIcon: "",
    whatsappLogoText: "বিকাশপেডিয়া হোৱাটছএপ (বাহ্যিক লিংক)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "বিকাশপিডিয়া ইউটিউব (বাহ্যিক লিংক)",
  },
  {
    languageShortName: "bn",
    aboutPortal1Text:
      "বিকাশপিডিয়া হল একটি দেশব্যাপী বহুভাষিক জ্ঞান-ভাগ করার প্ল্যাটফর্ম যা সামাজিক উন্নয়নের জন্য ডিজিটাল সংস্থান সরবরাহ করে। ",
    aboutPortal2Text: "এটি ভারত সরকারের উদ্যোগ এবং",
    aboutPortal3Text: "দ্বারা সম্পাদিত হয়েছে।",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "বিকাশপিডিয়া iOS অ্যাপ (বাহ্যিক লিঙ্ক)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (বহিরাগত লিঙ্ক)",
    cdacText: "সেন্টার ফর ডেভেলপমেন্ট অফ অ্যাডভান্সড কম্পিউটিং (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "ডিজিটাল ইন্ডিয়া (বাহ্যিক লিঙ্ক)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "বিকাশপিডিয়া ফেসবুক (বাহ্যিক লিঙ্ক)",
    hoverText: "Bengali",
    instagramIcon: InstagramIcon,
    instagramLogoText: "বিকাশপিডিয়া ইনস্টাগ্রাম (বাহ্যিক লিঙ্ক)",
    label: "বাংলা",
    lastmodified: "সর্বশেষ সংশোধিত",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "বিকাশপিডিয়া লিঙ্কডইন (বাহ্যিক লিঙ্ক)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (বাহ্যিক লিঙ্ক)",
    meityText: "ইলেকট্রনিক্স ও তথ্য প্রযুক্তি মন্ত্রকের (MeitY) ",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "বিকাশপিডিয়া অ্যান্ড্রয়েড অ্যাপ (বাহ্যিক লিঙ্ক)",
    searchButton: "খুঁজে দেখতে এখানে ক্লিক করুন",
    searchErrorText: "বিশেষ অক্ষর অনুমোদিত নয়",
    searchPlaceholderText: "অনুসন্ধান করার জন্য পাঠ্য লিখুন",
    searchText: "অনুসন্ধান",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "কৃষি",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ই-গভর্ন্যান্স",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "শিক্ষা",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "শক্তি",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "স্বাস্থ্য",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "সমাজ কল্যাণ",
        url: `https://xn--p5by0ags3b6blfceb.xn--45brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "সেক্টরগুলি",
    selectLanguageText: "ভাষা নির্বাচন করুন",
    twitterIcon: TwitterIcon,
    twitterLogoText: "বিকাশপিডিয়া টুইটার (বাহ্যিক লিঙ্ক)",
    urlAlternative: "",
    urlIdn: "https://xn--p5by0ags3b6blfceb.xn--45brj9c",
    urlLocal: "",
    urlSearch: "https://bn.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "2",
    vikaspediaLogoText: "বিকাশপিডিয়া",
    vikaspediaOfferedIn: "বিকাশপিডিয়াতে নিম্নলিখিত ভাষাগুলিতে কনটেন্ট আছে",
    whatsappIcon: "",
    whatsappLogoText: "বিকাশপিডিয়া হোয়াটসঅ্যাপ (বাহ্যিক লিঙ্ক)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "বিকাশপিডিয়া ইউটিউব (বাহ্যিক লিঙ্ক)",
  },
  {
    languageShortName: "brx",
    aboutPortal1Text:
      "Vikaspedia is a nationwide multilingual knowledge-sharing platform that provides digital resources for societal development.",
    aboutPortal2Text: "Government of India initiative executed by the",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "Vikaspedia iOS App (External link)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (External link)",
    cdacText: "Centre for Development of Advanced Computing (C-DAC).",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "Digital India (External link)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "Vikaspedia Facebook (External link)",
    hoverText: "Bodo",
    instagramIcon: InstagramIcon,
    instagramLogoText: "Vikaspedia Instagram (External link)",
    label: "बोडो",
    lastmodified: "Last Modified",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "Vikaspedia LinkedIn (External link)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (External link)",
    meityText: "Ministry of Electronics and Information Technology (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "Vikaspedia Android App (External link)",
    searchButton: "Click here to search",
    searchErrorText: "Special characters are not allowed",
    searchPlaceholderText: "Enter text to search",
    searchText: "Search",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "Agriculture",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "e-Governance",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "Education",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "Energy",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "Health",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "Social Welfare",
        url: `https://xn--11b8algs5c0becf0g.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "Sectors",
    selectLanguageText: "Select language",
    twitterIcon: TwitterIcon,
    twitterLogoText: "Vikaspedia X (External link)",
    urlAlternative: "",
    urlIdn: "https://xn--11b8algs5c0becf0g.xn--h2brj9c",
    urlLocal: "",
    urlSearch: "https://brx.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "3",
    vikaspediaLogoText: "Vikaspedia",
    vikaspediaOfferedIn: "Vikaspedia offered in",
    whatsappIcon: "",
    whatsappLogoText: "Vikaspedia WhatsApp (External link)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "Vikaspedia YouTube (External link)",
  },
  {
    languageShortName: "doi",
    aboutPortal1Text:
      "विकासपीडिया इक राष्ट्रव्यापी बहुभाषी ज्ञान साझा करने आह् ला मंच ऐ जेह् ड़ा समाज दे विकास आस्तै डिजिटल संसाधन उपलब्ध करोआंदा ऐ।",
    aboutPortal2Text: "भारत सरकार दी इक पैह् ल ऐ जेह् ड़ी",
    aboutPortal3Text: "आसेआ लागू कीती गेई ऐ।",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "विकासपीडिया आईओएस ऐप (बाह्य लिंक)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (बाह्य लिंक)",
    cdacText: "उन्नत कंप्यूटिंग विकास केंद्र (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "डिजिटल इंडिया (बाह्य लिंक)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "विकासपीडिया फेसबुक (बाह्य लिंक)",
    hoverText: "Dongri",
    instagramIcon: InstagramIcon,
    instagramLogoText: "विकासपीडिया इंस्टाग्राम (बाह्य लिंक)",
    label: "डोंगरी",
    lastmodified: "पिछली बारी संशोधित कीता गेआ",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "विकासपीडिया लिंक्डइन (बाह्य लिंक)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (बाह्य लिंक)",
    meityText: "इलेक्ट्रानिक्स ते सूचना प्रौद्योगिकी मंत्रालय (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "विकासपीडिया एंड्रॉयड ऐप (बाह्य लिंक)",
    searchButton: "खोज करने लेई इत्थै क्लिक करो",
    searchErrorText: "खास अक्षरें दी इजाजत नेईं ऐ",
    searchPlaceholderText: "खोज करने के लिए पाठ दर्ज करें",
    searchText: "खोजें",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "खेतीबाड़ी",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ई-गवर्नेंस",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "शिक्षा",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ऊर्जा",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "सेहत",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "समाज कल्याण",
        url: `https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "सेक्टरें दा",
    selectLanguageText: "भाषा चुनें",
    twitterIcon: TwitterIcon,
    twitterLogoText: "विकासपीडिया ट्विटर (बाह्य लिंक)",
    urlAlternative: "",
    urlIdn: "https://xn--31bt0c8c8b.xn--11by0av0at5becfj.xn--h2brj9c",
    urlLocal: "",
    urlSearch: "https://doi.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "4",
    vikaspediaLogoText: "विकासपीडिया",
    vikaspediaOfferedIn: "विकासपीडिया ने चढ़ाया में",
    whatsappIcon: "",
    whatsappLogoText: "विकासपीडिया व्हाट्सएप (बाह्य लिंक)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "विकासपीडिया यूट्यूब (बाह्य लिंक)",
  },
  {
    languageShortName: "en",
    aboutPortal1Text:
      "Vikaspedia is a nationwide multilingual knowledge-sharing platform that provides digital resources for societal development.",
    aboutPortal2Text: "Government of India initiative executed by the",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "Vikaspedia iOS App (External link)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (External link)",
    cdacText: "Centre for Development of Advanced Computing (C-DAC).",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "Digital India (External link)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "Vikaspedia Facebook (External link)",
    hoverText: "English",
    instagramIcon: InstagramIcon,
    instagramLogoText: "Vikaspedia Instagram (External link)",
    label: "English",
    lastmodified: "Last Modified",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "Vikaspedia LinkedIn (External link)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (External link)",
    meityText: "Ministry of Electronics and Information Technology (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "Vikaspedia Android App (External link)",
    searchButton: "Click here to search",
    searchErrorText: "Special characters are not allowed",
    searchPlaceholderText: "Enter text to search",
    searchText: "Search",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "Agriculture",
        url: `https://vikaspedia.in/agriculture`,
        value: "agriculture",
      },
      {
        hoverText: "Aspirational District",
        icon: LocationCityIcon,
        label: "Aspirational District",
        url: `https://vikaspedia.in/aspirational`,
        value: "aspirational",
      },
      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "e-Governance",
        url: `https://vikaspedia.in/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "Education",
        url: `https://vikaspedia.in/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "Energy",
        url: `https://vikaspedia.in/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "Health",
        url: `https://vikaspedia.in/health`,
        value: "health",
      },
      {
        hoverText: "Schemes",
        icon: ListAltIcon,
        label: "Schemes",
        url: `https://vikaspedia.in/schemes`,
        value: "schemes",
      },
      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "Social Welfare",
        url: `https://vikaspedia.in/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "Sectors",
    selectLanguageText: "Select language",
    twitterIcon: TwitterIcon,
    twitterLogoText: "Vikaspedia X (External link)",
    urlAlternative: "",
    urlIdn: "https://vikaspedia.in/InDG",
    urlLocal: "",
    urlSearch: "https://vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "5",
    vikaspediaLogoText: "Vikaspedia",
    vikaspediaOfferedIn: "Vikaspedia offered in",
    whatsappIcon: "",
    whatsappLogoText: "Vikaspedia WhatsApp (External link)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "Vikaspedia YouTube (External link)",
  },
  {
    languageShortName: "gu",
    aboutPortal1Text:
      "વિકાસપીડિયા એ રાષ્ટ્રવ્યાપી બહુભાષી જ્ઞાન-શેરિંગ પ્લેટફોર્મ છે જે સામાજિક વિકાસ માટે ડિજિટલ સંસાધનો પ્રદાન કરે છે.",
    aboutPortal2Text: "ની પહેલ છે.",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "વિકાસપીડિયા iOS એપ (બહારની કડી)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (બહારની કડી)",
    cdacText: "સેન્ટર ફોર ડેવલપમેન્ટ ઓફ એડવાન્સ્ડ કોમ્પ્યુટીંગ (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "ડિજિટલ ઈન્ડિયા (બહારની કડી)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "વિકાસપીડિયા ફેસબુક (બહારની કડી)",
    hoverText: "Gujarati",
    instagramIcon: InstagramIcon,
    instagramLogoText: "વિકાસપીડિયા ઇન્સ્ટાગ્રામ (બહારની કડી)",
    label: "ગુજરાતી",
    lastmodified: "છેલ્લે સુધારેલ",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "વિકાસપીડિયા લિન્ક્ડઇન (બહારની કડી)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (બહારની કડી)",
    meityText: "ઈલેક્ટ્રોનિક્સ અને ઈન્ફોર્મેશન ટેકનોલોજી (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "વિકાસપીડિયા એન્ડ્રોઇડ એપ (બહારની કડી)",
    searchButton: "શોધવા માટે અહીં ક્લિક કરો",
    searchErrorText: "વિશિષ્ અક્ષરોને મંજૂરી નથી",
    searchPlaceholderText: "શોધવા માટે ટેક્સ્ટ લખો",
    searchText: "સર્ચ કરો",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "કૃષિ",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ઇ-ગવર્નન્સ",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/e-governance`,
        value: "ઇ-ગવર્નન્સ",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "શિક્ષણ",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ઊર્જા",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "આરોગ્ય",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "સમાજ કલ્યાણ",
        url: `https://xn--0dcy0av0at5becfj.xn--gecrj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "ક્ષેત્રો",
    selectLanguageText: "એક ભાષા પસંદ કરો",
    twitterIcon: TwitterIcon,
    twitterLogoText: "વિકાસપીડિયા ટ્વિટર (બહારની કડી)",
    urlAlternative: "",
    urlIdn: "https://xn--0dcy0av0at5becfj.xn--gecrj9c",
    urlLocal: "",
    urlSearch: "https://gu.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "6",
    vikaspediaLogoText: "વિકાસપીડિયા",
    vikaspediaOfferedIn: "વિકાસપીડિયાએ ઓફર કરી હતી",
    whatsappIcon: "",
    whatsappLogoText: "વિકાસપીડિયા વોટ્સએપ (બહારની કડી)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "વિકાસપીડિયા યુટ્યુબ (બહારની કડી)",
  },
  {
    languageShortName: "hi",
    aboutPortal1Text:
      "विकासपीडिया एक बहुभाषी ज्ञान साझा करने वाला प्लेटफ़ॉर्म है जो सामाजिक विकास के लिए डिजिटल संसाधन प्रदान करता है।",
    aboutPortal2Text: "की एक पहल है जिसे",
    aboutPortal3Text: "द्वारा क्रियान्वित किया जाता है।",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "विकासपीडिया आईओएस ऐप (बाहरी लिंक)",
    cdacIcon: CdacIcon,
    cdacLogoText: "सी-डैक (बाहरी लिंक)",
    cdacText: "सेंटर फॉर डेवलपमेंट ऑफ़ एडवांस्ड कंप्यूटिंग (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "डिजिटल इंडिया (बाहरी लिंक)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "विकासपीडिया फेसबुक (बाहरी लिंक)",
    hoverText: "Hindi",
    instagramIcon: InstagramIcon,
    instagramLogoText: "विकासपीडिया इंस्टाग्राम (बाहरी लिंक)",
    label: "हिन्दी",
    lastmodified: "अंतिम बार संशोधित किया गया",
    lastmodifiedCdac: "सी-डैक",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "विकासपीडिया लिंक्डइन (बाहरी लिंक)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (बाहरी लिंक)",
    meityText: "इलेक्ट्रॉनिक्स और सूचना प्रौद्योगिकी मंत्रालय (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "विकासपीडिया एंड्रॉइड ऐप (बाहरी लिंक)",
    searchButton: "खोजने के लिए यहां क्लिक करें",
    searchErrorText: "विशेष वर्णों की अनुमति नहीं है",
    searchPlaceholderText: "खोजने के लिए पाठ दर्ज करें",
    searchText: "खोजें",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "कृषि",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },
      {
        hoverText: "Aspirational District",
        icon: LocationCityIcon,
        label: "आकांक्षात्मक जिला",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/aspirational`,
        value: "aspirational",
      },
      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ई-गवर्नेंस",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "शिक्षा",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ऊर्जा",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "स्वास्थ्य",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },
      {
        hoverText: "Schemes",
        icon: ListAltIcon,
        label: "योजनाओं",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/schemes`,
        value: "schemes",
      },
      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "सामाजिक कल्याण",
        url: `https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "सेक्टर्स",
    selectLanguageText: "भाषा चुने",
    twitterIcon: TwitterIcon,
    twitterLogoText: "विकासपीडिया ट्विटर (बाहरी लिंक)",
    urlAlternative: "",
    urlIdn: "https://xn--j2bd4cyah0f.xn--11by0av0at5becfj.xn--h2brj9c",
    urlLocal: "",
    urlSearch: "https://hi.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "7",
    vikaspediaLogoText: "विकासपीडिया",
    vikaspediaOfferedIn: "विकासपीडिया निम्नलिखित भाषाओं में उपलब्ध है।",
    whatsappIcon: "",
    whatsappLogoText: "विकासपीडिया व्हाट्सएप (बाहरी लिंक)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "विकासपीडिया यूट्यूब (बाहरी लिंक)",
  },
  {
    languageShortName: "kn",
    aboutPortal1Text:
      "ವಿಕಾಸ್‌ಪೀಡಿಯಾ ರಾಷ್ಟ್ರವ್ಯಾಪಿ ಬಹುಭಾಷಾ ಜ್ಞಾನ ಹಂಚಿಕೆ ವೇದಿಕೆಯಾಗಿದ್ದು ಅದು ಸಮಾಜದ ಅಭಿವೃದ್ಧಿಗೆ ಡಿಜಿಟಲ್ ಸಂಪನ್ಮೂಲಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ.",
    aboutPortal2Text: "ಇದು ಭಾರತ ಸರ್ಕಾರದ ಉಪಕ್ರಮವಾಗಿದ್ದು,",
    aboutPortal3Text: "ನಿಂದ ಜಾರಿಗೊಳಿಸಲಾಗಿದೆ.",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "ವಿಕಾಸ್ಪೀಡಿಯಾ iOS ಅಪ್ಲಿಕೇಶನ್ (ಬಾಹ್ಯ ಲಿಂಕ್)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (ಬಾಹ್ಯ ಲಿಂಕ್)",
    cdacText: "ಸೆಂಟರ್ ಫಾರ್ ಡೆವಲಪ್‌ಮೆಂಟ್ ಆಫ್ ಅಡ್ವಾನ್ಸ್‌ಡ್ ಕಂಪ್ಯೂಟಿಂಗ್ (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "ಡಿಜಿಟಲ್ ಇಂಡಿಯಾ (ಬಾಹ್ಯ ಲಿಂಕ್)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "ವಿಕಾಸ್‌ಪೀಡಿಯಾ ಫೇಸ್‌ಬುಕ್ (ಬಾಹ್ಯ ಲಿಂಕ್)",
    hoverText: "Kannada",
    instagramIcon: InstagramIcon,
    instagramLogoText: "ವಿಕಾಸ್‌ಪೀಡಿಯಾ ಇನ್‌ಸ್ಟಾಗ್ರಾಮ್ (ಬಾಹ್ಯ ಲಿಂಕ್)",
    label: "ಕನ್ನಡ",
    lastmodified: "ಕೊನೆಯದಾಗಿ ಮಾರ್ಪಡಿಸಿರುವುದು",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "ವಿಕಾಸಪೀಡಿಯಾ ಲಿಂಕ್ಡ್‌ಇನ್ (ಬಾಹ್ಯ ಲಿಂಕ್)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (ಬಾಹ್ಯ ಲಿಂಕ್)",
    meityText: "ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ಮಾಹಿತಿ ತಂತ್ರಜ್ಞಾನ ಸಚಿವಾಲಯದ (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "ವಿಕಾಸ್ಪೀಡಿಯಾ ಆಂಡ್ರಾಯ್ಡ್ ಅಪ್ಲಿಕೇಶನ್ (ಬಾಹ್ಯ ಲಿಂಕ್)",
    searchButton: "ಹುಡುಕಲು ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ",
    searchErrorText: "ವಿಶೇಷ ಅಕ್ಷರಗಳನ್ನು ಅನುಮತಿಸಲಾಗುವುದಿಲ್ಲ",
    searchPlaceholderText: "ಹುಡುಕಾಟಕ್ಕೆ ಪಠ್ಯವನ್ನು ನಮೂದಿಸಿ",
    searchText: "ಹುಡುಕು",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "ಕೃಷಿ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ಇ-ಆಡಳಿತ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "ಶಿಕ್ಷಣ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ಶಕ್ತಿ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "ಆರೋಗ್ಯ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "ಸಮಾಜ ಕಲ್ಯಾಣ",
        url: `https://xn--nscy0av0at5bgfi5l.xn--2scrj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "ವಲಯಗಳು",
    selectLanguageText: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    twitterIcon: TwitterIcon,
    twitterLogoText: "ವಿಕಾಸ್ಪೀಡಿಯಾ ಟ್ವಿಟರ್ (ಬಾಹ್ಯ ಲಿಂಕ್)",
    urlAlternative: "",
    urlIdn: "https://xn--nscy0av0at5bgfi5l.xn--2scrj9c",
    urlLocal: "",
    urlSearch: "https://kn.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "8",
    vikaspediaLogoText: "ವಿಕಾಸಪೀಡಿಯಾ",
    vikaspediaOfferedIn: "ವಿಕಾಸಪೀಡಿಯಾ ದಲ್ಲಿ ನೀಡಲಾಗುವ ಭಾಷೆಗಳು",
    whatsappIcon: "",
    whatsappLogoText: "ವಿಕಾಸ್‌ಪೀಡಿಯಾ ವಾಟ್ಸಾಪ್ (ಬಾಹ್ಯ ಲಿಂಕ್)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "ವಿಕಾಸ್ ಪೀಡಿಯಾ ಯೂಟ್ಯೂಬ್ (ಬಾಹ್ಯ ಲಿಂಕ್)",
  },
  {
    languageShortName: "kok",
    aboutPortal1Text:
      "विकासपीडिया हें देशभरांतलें बहुभाषी गिन्यान वांटपाचें मंच आसा जें समाजाचे उदरगती खातीर डिजिटल साधनां दिता.",
    aboutPortal2Text: "भारत सरकाराचो हो एक उपक्रम आसून तो",
    aboutPortal3Text: "हांणी चालीक लायला.",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "विकासपीडिया iOS एप (बाह्य दुवो)",
    cdacIcon: CdacIcon,
    cdacLogoText: "सी-डीएसी (बाह्य दुवो)",
    cdacText: "सेंटर फॉर डेव्हलपमेंट ऑफ अॅडव्हान्सड कंप्यूटिंग (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "डिजिटल इंडिया (बाह्य दुवो)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "विकासपीडिया फेसबूक (बाह्य दुवो)",
    hoverText: "Konkani",
    instagramIcon: InstagramIcon,
    instagramLogoText: "विकासपीडिया इंस्टाग्राम (बाह्य दुवो)",
    label: "कोंकणी",
    lastmodified: "निमाणें बदल केल्लें",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "विकासपीडिया लिंक्डइन (बाह्य दुवो)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (बाह्य दुवो)",
    meityText: "इलॅक्ट्रॉनिक्स आनी म्हायती तंत्रज्ञान मंत्रालय (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "विकासपीडिया एंड्रॉयड एप (बाह्य लिंक)",
    searchButton: "सोदपाक हांगा क्लिक करात",
    searchErrorText: "खाशेल्या अक्षरांक परवानगी ना",
    searchPlaceholderText: "सोदपाक मजकूर दाखयात",
    searchText: "सोद",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "शेती",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ई-गव्हर्नन्स",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "शिक्षण",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "उर्जा",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "भलायकी",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "समाज कल्याण",
        url: `https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "क्षेत्रां",
    selectLanguageText: "भास वेंचून काडची",
    twitterIcon: TwitterIcon,
    twitterLogoText: "विकासपीडिया ट्विटर (बाह्य दुवो)",
    urlAlternative: "",
    urlIdn: "https://xn--i1b1bb0d0hoc.xn--11by0av0at5becfj.xn--h2brj9c",
    urlLocal: "",
    urlSearch: "https://kok.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "10",
    vikaspediaLogoText: "विकासपीडिया",
    vikaspediaOfferedIn: "विकासपीडियांत अर्पण करतात",
    whatsappIcon: "",
    whatsappLogoText: "विकासपीडिया व्हॉट्सअॅप (बाह्य लिंक)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "विकासपीडिया युट्युब (बाह्य दुवो)",
  },
  {
    languageShortName: "ks",
    aboutPortal1Text:
      "Vikaspedia is a nationwide multilingual knowledge-sharing platform that provides digital resources for societal development.",
    aboutPortal2Text: "Government of India initiative executed by the",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "Vikaspedia iOS App (External link)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (External link)",
    cdacText: "Centre for Development of Advanced Computing (C-DAC).",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "Digital India (External link)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "Vikaspedia Facebook (External link)",
    hoverText: "Kashmiri",
    instagramIcon: InstagramIcon,
    instagramLogoText: "Vikaspedia Instagram (External link)",
    label: "كٲشُر",
    lastmodified: "Last Modified",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "Vikaspedia LinkedIn (External link)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (External link)",
    meityText: "Ministry of Electronics and Information Technology (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "Vikaspedia Android App (External link)",
    searchButton: "Click here to search",
    searchErrorText: "Special characters are not allowed",
    searchPlaceholderText: "Enter text to search",
    searchText: "Search",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "Agriculture",
        url: `https://ks.vikaspedia.in/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "e-Governance",
        url: `https://ks.vikaspedia.in/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "Education",
        url: `https://ks.vikaspedia.in/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "Energy",
        url: `https://ks.vikaspedia.in/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "Health",
        url: `https://ks.vikaspedia.in/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "Social Welfare",
        url: `https://ks.vikaspedia.in/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "Sectors",
    selectLanguageText: "Select language",
    twitterIcon: TwitterIcon,
    twitterLogoText: "Vikaspedia X (External link)",
    urlAlternative: "",
    urlIdn: "https://ks.vikaspedia.in",
    urlLocal: "",
    urlSearch: "https://ks.vikaspedia.in/populer-topics/",
    urlSubDomain: "https://xn----ymcb0c2fvdtnxczo9lc.xn--mgbbh1a/",
    value: "9",
    vikaspediaLogoText: "Vikaspedia",
    vikaspediaOfferedIn: "Vikaspedia offered in",
    whatsappIcon: "",
    whatsappLogoText: "Vikaspedia WhatsApp (External link)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "Vikaspedia YouTube (External link)",
  },
  {
    languageShortName: "mai",
    aboutPortal1Text:
      "विकासपीडिया एकटा राष्ट्रव्यापी बहुभाषी ज्ञान साझा करय वाला मंच छै जे समाज के विकास के लेल डिजिटल संसाधन उपलब्ध कराबै छै.",
    aboutPortal2Text: "इ भारत सरकार कें ,कें पहल छै जे",
    aboutPortal3Text: "द्वारा लागू कैल गेल छै.",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "विकासपीडिया आईओएस ऐप (बाहरी लिंक)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (बाहरी लिंक)",
    cdacText: "सेंटर फॉर डेवलपमेंट ऑफ एडवांस्ड कंप्यूटिंग (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "डिजिटल इंडिया (बाह्य लिंक)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "विकासपीडिया फेसबुक (बाह्य लिंक)",
    hoverText: "Maithili",
    instagramIcon: InstagramIcon,
    instagramLogoText: "विकासपीडिया इन्स्टाग्राम (बाहरी लिंक)",
    label: "मैथिली",
    lastmodified: "अंतिम परिवर्तन",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "विकासपीडिया लिंक्डइन (बाह्य लिंक)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (बाहरी लिंक)",
    meityText: "इलेक्ट्रॉनिक्स आ सूचना प्रौद्योगिकी मंत्रालय (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "विकासपीडिया एंड्रॉयड ऐप (बाहरी लिंक)",
    searchButton: "खोजबाक लेल एतय क्लिक करू",
    searchErrorText: "विशेष वर्णक अनुमति नहि अछि",
    searchPlaceholderText: "खोज करबाक लेल पाठ दर्ज करू",
    searchText: "खोजनाइ",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "खेती",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ई-शासन",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "शिक्षा",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "उर्जा",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "स्वास्थ्य",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "समाज कल्याण",
        url: `https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "क्षेत्रों के लिये",
    selectLanguageText: "भाषा चुनें",
    twitterIcon: TwitterIcon,
    twitterLogoText: "विकासपीडिया ट्विटर (बाह्य लिंक)",
    urlAlternative: "",
    urlIdn: "https://xn--i2brn5cg8b.xn--11by0av0at5becfj.xn--h2brj9c",
    urlLocal: "",
    urlSearch: "https://mai.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "11",
    vikaspediaLogoText: "विकासपीडिया",
    vikaspediaOfferedIn: "विकासपीडिया में अर्पित",
    whatsappIcon: "",
    whatsappLogoText: "विकासपीडिया व्हाट्सएप (बाहरी लिंक)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "विकासपीडिया यूट्यूब (बाह्य लिंक)",
  },
  {
    languageShortName: "ml",
    aboutPortal1Text:
      "വികാസ്-പീഡിയ എന്നത് സാമൂഹിക വികസനത്തിന് ഡിജിറ്റൽ ഉപാധികൾ നൽകുന്ന ഒരു ബഹുഭാഷാ വിജ്ഞാന പങ്കിടൽ പ്ലാറ്റ്‌ഫോമാണ്.",
    aboutPortal2Text: " ഇന്ത്യാ ഗവൺമെൻ്റ്, തുടിങ്ങിവച്ച ഈ സംരംഭം",
    aboutPortal3Text: "ആണ് നടപ്പിലാക്കുന്നത്.",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "വികാസ്-പീഡിയ iOS ആപ്പ് (ബാഹ്യ ലിങ്ക്)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (ബാഹ്യ ലിങ്ക്)",
    cdacText:
      "സെൻ്റർ ഫോർ ഡെവലപ്‌മെൻ്റ് ഓഫ് അഡ്വാൻസ്‌ഡ് കംപ്യൂട്ടിംഗ് (സി-ഡാക്)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "ഡിജിറ്റൽ ഇന്ത്യ (ബാഹ്യ ലിങ്ക്)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "വികാസ്-പീഡിയ ഫേസ്ബുക്ക് (ബാഹ്യ ലിങ്ക്)",
    hoverText: "Malayalam",
    instagramIcon: InstagramIcon,
    instagramLogoText: "വികാസ്-പീഡിയ ഇൻസ്റ്റാഗ്രാം (ബാഹ്യ ലിങ്ക്)",
    label: "മലയാളം",
    lastmodified: "അവസാനം പരിഷ്കരിച്ചത്",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "വികാസ്-പീഡിയ ലിങ്ക്ഡ്ഇൻ (ബാഹ്യ ലിങ്ക്)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (ബാഹ്യ ലിങ്ക്)",
    meityText: "ഇലക്‌ട്രോണിക്‌സ് ആൻ്റ് ഇൻഫർമേഷൻ ടെക്‌നോളജി (MeitY) മന്ത്രാലയം",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "വികാസ്-പീഡിയ ആൻഡ്രോയിഡ് ആപ്പ് (ബാഹ്യ ലിങ്ക്)",
    searchButton: "തിരയാൻ ഇവിടെ ക്ലിക്ക് ചെയ്യുക",
    searchErrorText: "പ്രത്യേക പ്രതീകങ്ങൾ അനുവദനീയമല്ല",
    searchPlaceholderText: "തിരയാൻ വാചകങ്ങൾ നൽകുക",
    searchText: "തിരയുക",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "കൃഷി",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ഇ-ഭരണനിർവ്വഹണം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "വിദ്യാഭ്യാസം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ഊർജ്ജം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "ആരോഗ്യം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "സാമൂഹ്യക്ഷേമം",
        url: `https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "മേഖലകൾ",
    selectLanguageText: "ഭാഷ തിരഞ്ഞെടുക്കുക",
    twitterIcon: TwitterIcon,
    twitterLogoText: "വികാസ്-പീഡിയ ട്വിറ്റർ (ബാഹ്യ ലിങ്ക്)",
    urlAlternative: "",
    urlIdn: "https://xn----cjf1b9a0a5aw1chgj7m.xn--rvc1e0am3e",
    urlLocal: "",
    urlSearch: "https://ml.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "12",
    vikaspediaLogoText: "വികാസ്-പീഡിയ",
    vikaspediaOfferedIn: "വികാസ്-പീഡിയ ഭാഷാ ലഭ്യത",
    whatsappIcon: "",
    whatsappLogoText: "വികാസ്-പീഡിയ വാട്ട്‌സ്ആപ്പ് (ബാഹ്യ ലിങ്ക്)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "വികാസ്-പീഡിയ യൂട്യൂബ് (ബാഹ്യ ലിങ്ക്)",
  },
  {
    languageShortName: "mni",
    aboutPortal1Text:
      "Vikaspedia is a nationwide multilingual knowledge-sharing platform that provides digital resources for societal development.",
    aboutPortal2Text: "Government of India initiative executed by the",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "Vikaspedia iOS App (External link)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (External link)",
    cdacText: "Centre for Development of Advanced Computing (C-DAC).",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "Digital India (External link)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "Vikaspedia Facebook (External link)",
    hoverText: "Manipuri",
    instagramIcon: InstagramIcon,
    instagramLogoText: "Vikaspedia Instagram (External link)",
    label: "মণিপুরি",
    lastmodified: "Last Modified",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "Vikaspedia LinkedIn (External link)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (External link)",
    meityText: "Ministry of Electronics and Information Technology (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "Vikaspedia Android App (External link)",
    searchButton: "Click here to search",
    searchErrorText: "Special characters are not allowed",
    searchPlaceholderText: "Enter text to search",
    searchText: "Search",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "Agriculture",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "e-Governance",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "Education",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "Energy",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "Health",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "Social Welfare",
        url: `https://xn--p5b8algs5c5alfceb.xn--45brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "Sectors",
    selectLanguageText: "Select language",
    twitterIcon: TwitterIcon,
    twitterLogoText: "Vikaspedia X (External link)",
    urlAlternative: "",
    urlIdn: "https://xn--p5b8algs5c5alfceb.xn--45brj9c",
    urlLocal: "",
    urlSearch: "https://mni.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "13",
    vikaspediaLogoText: "Vikaspedia",
    vikaspediaOfferedIn: "Vikaspedia offered in",
    whatsappIcon: "",
    whatsappLogoText: "Vikaspedia WhatsApp (External link)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "Vikaspedia YouTube (External link)",
  },
  {
    languageShortName: "mr",
    aboutPortal1Text:
      "विकासपीडिया हे बहुभाषिक ज्ञान सामायिकरण व्यासपीठ आहे जे सामाजिक विकासासाठी डिजिटल संसाधने प्रदान करते.",
    aboutPortal2Text: " हा भारत सरकारच्या ,उपक्रम आहे जो",
    aboutPortal3Text: "द्वारे राबविला जातो.",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "विकासपीडिया iOS ॲप (बाह्य लिंक)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (बाह्य लिंक)",
    cdacText: "सेंटर फॉर डेव्हलपमेंट ऑफ ॲडव्हान्स्ड कॉम्प्युटिंग (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "डिजिटल इंडिया (बाह्य लिंक)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "विकासपीडिया फेसबुक (बाह्य लिंक)",
    hoverText: "Marathi",
    instagramIcon: InstagramIcon,
    instagramLogoText: "विकासपीडिया इंस्टाग्राम (बाह्य लिंक)",
    label: "मराठी",
    lastmodified: "शेवटचे सुधारित",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "विकासपीडिया लिंक्डइन (बाह्य लिंक)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (बाह्य लिंक)",
    meityText: "इलेक्ट्रॉनिक्स आणि माहिती तंत्रज्ञान मंत्रालयाचा (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "विकासपीडिया अँड्रॉइड ॲप (बाह्य लिंक)",
    searchButton: "शोधण्यासाठी येथे क्लिक करा",
    searchErrorText: "विशेष वर्णांना अनुमती नाही",
    searchPlaceholderText: "शोधण्यासाठी मजकूर प्रविष्ट करा",
    searchText: "शोध",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "शेती",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ई-गव्हर्नन्स",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "शिक्षण",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ऊर्जा",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "आरोग्य",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "सामाजिक कल्याण",
        url: `https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "सेक्टर्स",
    selectLanguageText: "निवडा भाषा",
    twitterIcon: TwitterIcon,
    twitterLogoText: "विकासपीडिया ट्विटर (बाह्य लिंक)",
    urlAlternative: "",
    urlIdn: "https://xn--d2b1ag0dl.xn--11by0av0at5becfj.xn--h2brj9c",
    urlLocal: "",
    urlSearch: "https://mr.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "14",
    vikaspediaLogoText: "विकासपीडिया",
    vikaspediaOfferedIn:
      "विकासपीडिया खाली सूचीबद्ध केलेल्या भाषांमध्ये उपलब्ध आहे.",
    whatsappIcon: "",
    whatsappLogoText: "विकासपीडिया व्हॉट्सॲप (बाह्य लिंक)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "विकासपीडिया यूट्यूब (बाह्य लिंक)",
  },
  {
    languageShortName: "ne",
    aboutPortal1Text:
      "विकासपिडिया एक राष्ट्रव्यापी बहुभाषिक ज्ञान साझेदारी प्लेटफर्म हो जसले समाजको विकासको लागि डिजिटल स्रोतहरू प्रदान गर्दछ।",
    aboutPortal2Text:
      "यो उन्नत कम्प्युटिङको विकास केन्द्र (C-DAC) द्वारा लागू गरिएको भारत सरकारको इलेक्ट्रोनिक्स र सूचना प्रविधि मन्त्रालय (MeitY) को पहल हो।",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "विकासपेडिया iOS एप (बाह्य लिङ्क)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (बाह्य लिङ्क)",
    cdacText: "",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "डिजिटल भारत (बाह्य लिंक)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "विकासपेडिया फेसबुक (बाह्य लिङ्क)",
    hoverText: "Nepali",
    instagramIcon: InstagramIcon,
    instagramLogoText: "विकासपेडिया इन्स्टाग्राम (बाह्य लिङ्क)",
    label: "नेपाली",
    lastmodified: "पछिल्लो पटक परिमार्जित",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "विकासपेडिया लिंक्डइन (बाह्य लिंक)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (बाह्य लिङ्क)",
    meityText: "",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "विकासपेडिया एन्ड्रोइड एप (बाह्य लिङ्क)",
    searchButton: "खोज्न यहाँ क्लिक गर्नुहोस्",
    searchErrorText: "विशेष क्यारेक्टरहरू अनुमति छैन",
    searchPlaceholderText: "खोजी गर्न पाठ प्रविष्ट गर्नुहोस्",
    searchText: "खोज",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "कृषि",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ई-शासन",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "शिक्षा",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ऊर्जा",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "स्वास्थ्य",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "सामाजिक कल्याण",
        url: `https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "क्षेत्रहरू",
    selectLanguageText: "भाषा छनोट गर्नुस",
    twitterIcon: TwitterIcon,
    twitterLogoText: "विकासपेडिया ट्विटर (बाह्य लिङ्क)",
    urlAlternative: "",
    urlIdn: "https://xn--l2bey1cl2b.xn--11by0av0at5becfj.xn--h2brj9c",
    urlLocal: "",
    urlSearch: "https://ne.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "15",
    vikaspediaLogoText: "विकासपिडिया",
    vikaspediaOfferedIn: "विकासपेडिया मा प्रस्तावित",
    whatsappIcon: "",
    whatsappLogoText: "विकासपेडिया व्हाट्सएप (बाह्य लिंक)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "विकासपेडिया यूट्यूब (बाह्य लिङ्क)",
  },
  {
    languageShortName: "or",
    aboutPortal1Text:
      "ବିକାଶପେଡିଆ ହେଉଛି ଏକ ଦେଶବ୍ୟାପୀ ବହୁଭାଷୀ ଜ୍ଞାନ ବଣ୍ଟନ ପ୍ଲାଟଫର୍ମ ଯାହା ସାମାଜିକ ବିକାଶ ପାଇଁ ଡିଜିଟାଲ୍ ଉତ୍ସ ଯୋଗାଇଥାଏ|",
    aboutPortal2Text: " ଏହା ହେଉଛି ,ଭାରତ ସରକାରଙ୍କ",
    aboutPortal3Text: "ଦ୍ୱାରା ପରିଚାଳିତ |",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "ବିକାଶପେଡିଆ iOS ଆପ୍ (ବାହ୍ୟ ଲିଙ୍କ୍)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (ବାହ୍ୟ ଲିଙ୍କ୍)",
    cdacText: "ସେଣ୍ଟର ଫର ଡେଭଲପମେଣ୍ଟ ଅଫ୍ ଆଡଭାନ୍ସଡ କମ୍ପ୍ୟୁଟିଙ୍ଗ୍ (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "ଡିଜିଟାଲ୍ ଇଣ୍ଡିଆ (ବାହ୍ୟ ଲିଙ୍କ୍)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "ବିକାଶପେଡିଆ ଫେସବୁକ୍ (ବାହ୍ୟ ଲିଙ୍କ୍)",
    hoverText: "Odia",
    instagramIcon: InstagramIcon,
    instagramLogoText: "ବିକାଶପେଡିଆ ଇନଷ୍ଟାଗ୍ରାମ (ବାହ୍ୟ ଲିଙ୍କ୍)",
    label: "ଓଡ଼ିଆ",
    lastmodified: "ଶେଷ ରୂପାନ୍ତରିତ ",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "ବିକାଶପେଡିଆ ଲିଙ୍କଡଇନ୍ (ବାହ୍ୟ ଲିଙ୍କ୍)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (ବାହ୍ୟ ଲିଙ୍କ୍)",
    meityText: "ଇଲେକ୍ଟ୍ରୋନିକ୍ସ ଏବଂ ସୂଚନା ପ୍ରଯୁକ୍ତିବିଦ୍ୟା ମନ୍ତ୍ରଣାଳୟ (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "ବିକାଶପେଡିଆ ଆଣ୍ଡ୍ରଏଡ୍ ଆପ୍ (ବାହ୍ୟ ଲିଙ୍କ୍)",
    searchButton: "ଖୋଜିବାକୁ ଏଠାରେ କ୍ଲିକ୍ କରନ୍ତୁ",
    searchErrorText: "ବିଶେଷ ବର୍ଣ୍ଣଗୁଡିକ ଅନୁମତିପ୍ରାପ୍ତ ନୁହେଁ",
    searchPlaceholderText: "ସନ୍ଧାନ କରିବାକୁ ପାଠ ପ୍ରବେଶ କରନ୍ତୁ",
    searchText: "ଖୋଜ",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "କୃଷି",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ଇ-ଶାସନ",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "ଶିକ୍ଷା",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ଶକ୍ତି",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "ସ୍ୱାସ୍ଥ୍ୟ",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "ସାମାଜିକ କଲ୍ୟାଣ",
        url: `https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "କ୍ଷେତ୍ରଗୁଡିକ",
    selectLanguageText: "ଭାଷା ଚୟନ କରନ୍ତୁ",
    twitterIcon: TwitterIcon,
    twitterLogoText: "ବିକାଶପେଡିଆ ଟ୍ୱିଟର (ବାହ୍ୟ ଲିଙ୍କ)",
    urlAlternative: "",
    urlIdn: "https://xn--8gc3ayb9ai5d1bmhec.xn--3hcrj9c",
    urlLocal: "",
    urlSearch: "https://or.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "16",
    vikaspediaLogoText: "ବିକାଶପେଡିଆ",
    vikaspediaOfferedIn: "ବିକାଶପେଡିଆ ଉପଲବ୍ଧ କରାଯାଇଛି",
    whatsappIcon: "",
    whatsappLogoText: "ବିକାଶପେଡିଆ ୱ୍ୟାଟସାପ୍ (ବାହ୍ୟ ଲିଙ୍କ୍)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "ବିକାଶପେଡିଆ ୟୁଟ୍ୟୁବ୍ (ବାହ୍ୟ ଲିଙ୍କ୍)",
  },
  {
    languageShortName: "pa",
    aboutPortal1Text:
      "ਵਿਕਾਸਪੀਡੀਆ ਇੱਕ ਦੇਸ਼ ਵਿਆਪੀ ਬਹੁ-ਭਾਸ਼ਾਈ ਗਿਆਨ ਸਾਂਝਾ ਕਰਨ ਵਾਲਾ ਪਲੇਟਫਾਰਮ ਹੈ ਜੋ ਸਮਾਜ ਦੇ ਵਿਕਾਸ ਲਈ ਡਿਜੀਟਲ ਸਰੋਤ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।",
    aboutPortal2Text:
      "ਇਹ ਸੈਂਟਰ ਫਾਰ ਡਿਵੈਲਪਮੈਂਟ ਆਫ ਐਡਵਾਂਸਡ ਕੰਪਿਊਟਿੰਗ (C-DAC) ਦੁਆਰਾ ਲਾਗੂ ਭਾਰਤ ਸਰਕਾਰ ਦੇ ਇਲੈਕਟ੍ਰਾਨਿਕਸ ਅਤੇ ਸੂਚਨਾ ਤਕਨਾਲੋਜੀ ਮੰਤਰਾਲੇ (MeitY) ਦੀ ਇੱਕ ਪਹਿਲ ਹੈ।",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "ਵਿਕਾਸਪੀਡੀਆ iOS ਐਪ (ਬਾਹਰੀ ਲਿੰਕ)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (ਬਾਹਰੀ ਲਿੰਕ)",
    cdacText: "",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "ਡਿਜੀਟਲ ਇੰਡੀਆ (ਬਾਹਰੀ ਲਿੰਕ)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "ਵਿਕਾਸਪੀਡੀਆ ਫੇਸਬੁੱਕ (ਬਾਹਰੀ ਲਿੰਕ)",
    hoverText: "Punjabi",
    instagramIcon: InstagramIcon,
    instagramLogoText: "ਵਿਕਾਸਪੀਡੀਆ ਇੰਸਟਾਗ੍ਰਾਮ (ਬਾਹਰੀ ਲਿੰਕ)",
    label: "ਪੰਜਾਬੀ",
    lastmodified: "ਪਿਛਲੀ ਵਾਰ ਸੋਧਿਆ ਗਿਆ",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "ਵਿਕਾਸਪੀਡੀਆ ਲਿੰਕਡਇਨ (ਬਾਹਰੀ ਲਿੰਕ)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (ਬਾਹਰੀ ਲਿੰਕ)",
    meityText: "",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "ਵਿਕਾਸਪੀਡੀਆ ਐਂਡਰਾਇਡ ਐਪ (ਬਾਹਰੀ ਲਿੰਕ)",
    searchButton: "ਖੋਜ ਕਰਨ ਲਈ ਇੱਥੇ ਕਲਿੱਕ ਕਰੋ",
    searchErrorText: "ਵਿਸ਼ੇਸ਼ ਅੱਖਰ-ਚਿੰਨ੍ਹਾਂ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਹੈ",
    searchPlaceholderText: "ਖੋਜ ਕਰਨ ਲਈ ਟੈਕਸਟ ਦਰਜ ਕਰੋ",
    searchText: "ਖੋਜ",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "ਖੇਤੀਬਾੜੀ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ਈ-ਗਵਰਨੈਂਸ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "ਸਿੱਖਿਆ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ਊਰਜਾ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "ਸਿਹਤ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "ਸਮਾਜਿਕ ਭਲਾਈ",
        url: `https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "ਸੈਕਟਰਾਂ",
    selectLanguageText: "ਭਾਸ਼ਾ ਦੀ ਚੋਣ ਕਰੋ",
    twitterIcon: TwitterIcon,
    twitterLogoText: "ਵਿਕਾਸਪੀਡੀਆ ਟਵਿੱਟਰ (ਬਾਹਰੀ ਲਿੰਕ)",
    urlAlternative: "",
    urlIdn: "https://xn--x8b3ayb9a3ct5bgnb.xn--s9brj9c",
    urlLocal: "",
    urlSearch: "https://pa.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "17",
    vikaspediaLogoText: "ਵਿਕਾਸਪੀਡੀਆ",
    vikaspediaOfferedIn: "ਵਿਕਾਸਪੀਡੀਆ ਵਿੱਚ ਪੇਸ਼ਕਸ਼ ਕੀਤੀ ਗਈ",
    whatsappIcon: "",
    whatsappLogoText: "ਵਿਕਾਸਪੀਡੀਆ ਵਟਸਐਪ (ਬਾਹਰੀ ਲਿੰਕ)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "ਵਿਕਾਸਪੀਡੀਆ ਯੂਟਿਊਬ (ਬਾਹਰੀ ਲਿੰਕ)",
  },
  {
    languageShortName: "sa",
    aboutPortal1Text:
      "विकासपीडिया राष्ट्रव्यापी बहुभाषिकज्ञानसाझेदारीमञ्चः अस्ति यः समाजस्य विकासाय अङ्कीयसंसाधनं प्रदाति।",
    aboutPortal2Text: " इयं भारतसर्वकारस्य |उपक्रमः अस्ति, या",
    aboutPortal3Text: "कार्यान्विता अस्ति ।",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "विकासपीडिया iOS App (बाह्य लिंक)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (बाह्यलिङ्कम्) २.",
    cdacText: "उन्नत-कम्प्यूटिङ्ग-विकास-केन्द्रेन (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "अङ्कीय भारत (बाह्यलिङ्क) २.",
    facebookIcon: FacebookIcon,
    facebookLogoText: "विकासपीडिया फेसबुक (बाह्यलिङ्क)",
    hoverText: "Sanskrit",
    instagramIcon: InstagramIcon,
    instagramLogoText: "विकासपीडिया इन्स्टाग्राम (बाह्य लिंक)",
    label: "संस्कृत",
    lastmodified: "अन्तिम परिवर्तनं कृतम्",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "विकासपीडिया लिङ्क्डइन (बाह्यलिङ्क)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (बाह्यलिङ्क) .",
    meityText: "इलेक्ट्रॉनिक्स-सूचना-प्रौद्योगिकी-मन्त्रालयस्य (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "विकासपीडिया एण्ड्रॉयड् एप् (बाह्य लिङ्क)",
    searchButton: "अन्वेषणार्थम् अत्र क्लिक् कुर्वन्तु",
    searchErrorText: "विशेषवर्णानां अनुमतिः नास्ति",
    searchPlaceholderText: "अन्वेषणार्थं पाठं प्रविष्टं कुर्वन्तु",
    searchText: "अन्वेषण",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "कृषि",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ई-शासनम्",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "शिक्षा",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "ऊर्जाम्",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "स्वास्थ्यम्",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "समाज कल्याण",
        url: `https://xn--11by0av0at5becfj.xn--h2breg3eve/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "क्षेत्राणि",
    selectLanguageText: "भाषा चयनं कुर्वन्तु",
    twitterIcon: TwitterIcon,
    twitterLogoText: "विकासपीडिया ट्विट्टर्(बाह्यलिङ्काः)",
    urlAlternative: "",
    urlIdn: "https://xn--11by0av0at5becfj.xn--h2breg3eve",
    urlLocal: "",
    urlSearch: "https://sa.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "18",
    vikaspediaLogoText: "विकासपीडिया",
    vikaspediaOfferedIn: "विकासपीडियायां अर्पितः",
    whatsappIcon: "",
    whatsappLogoText: "विकासपीडिया व्हाट्सएप्प (बाह्य लिंक)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "विकासपीडिया यूट्यूब (बाह्यलिङ्क)",
  },
  {
    languageShortName: "sat",
    aboutPortal1Text:
      "Vikaspedia is a nationwide multilingual knowledge-sharing platform that provides digital resources for societal development.",
    aboutPortal2Text: "Government of India initiative executed by the",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "Vikaspedia iOS App (External link)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (External link)",
    cdacText: "Centre for Development of Advanced Computing (C-DAC).",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "Digital India (External link)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "Vikaspedia Facebook (External link)",
    hoverText: "Santali",
    instagramIcon: InstagramIcon,
    instagramLogoText: "Vikaspedia Instagram (External link)",
    label: "ᱥᱟᱱᱛᱟᱲᱤ",
    lastmodified: "Last Modified",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "Vikaspedia LinkedIn (External link)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (External link)",
    meityText: "Ministry of Electronics and Information Technology (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "Vikaspedia Android App (External link)",
    searchButton: "Click here to search",
    searchErrorText: "Special characters are not allowed",
    searchPlaceholderText: "Enter text to search",
    searchText: "Search",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "Agriculture",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "e-Governance",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "Education",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "Energy",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "Health",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "Social Welfare",
        url: `https://xn--11by0av0at5becfj.xn--h2brj9c8c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "Sectors",
    selectLanguageText: "Select language",
    twitterIcon: TwitterIcon,
    twitterLogoText: "Vikaspedia X (External link)",
    urlAlternative: "",
    urlIdn: "https://xn--11by0av0at5becfj.xn--h2brj9c8c",
    urlLocal: "",
    urlSearch: "https://sat.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "19",
    vikaspediaLogoText: "Vikaspedia",
    vikaspediaOfferedIn: "Vikaspedia offered in",
    whatsappIcon: "",
    whatsappLogoText: "Vikaspedia WhatsApp (External link)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "Vikaspedia YouTube (External link)",
  },
  {
    languageShortName: "sd",
    aboutPortal1Text:
      "विकासपीडया हिक मुल्कु वारे ख़्ली लिसानी इलम जे हिसेदारी वारो प्लेट फ़ार्म आहे जेको समाजी तरिक़ी लाइ डिजीटल वसीला फ़राहमु करे थो.",
    aboutPortal2Text:
      ". इहो बर्क़ी ऐं इन्फ़ार्मेशन टेक्नालाजी वारी वज़ारत आहे (MeitY) इंडिया जी हुकूमत सेन्टर फ़ार डेवलपमंट ऑफ़ एडवांस्ड कम्प्यूटिंग (से डी ए से पारां अमलु कयो व्यो..",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "विकासपीडयाiOS एप्प (ख़ारजी लिंक)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (ख़ारजी लिंक)",
    cdacText: "",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "डिजीटल इंडिया (ख़ारजी लिंक)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "विकासपीडया फ़ेसबुक (ख़ारजी लिंक)",
    hoverText: "Sindhi",
    instagramIcon: InstagramIcon,
    instagramLogoText: "विकासपीडया इंस्टाग्राम (ख़ारजी लिंक)",
    label: "सिंधी",
    lastmodified: "आख़िरी तरमीम कई वई",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "विकासपीडया Linkedin (ख़ारजी लिंक)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (ख़ारजी लिंक)",
    meityText: "",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "विकासपीडया एंड्राइड एप्प (ख़ारजी लिंक)",
    searchButton: "ॻोलन लाइ हिते क्लिक कयो",
    searchErrorText: "ख़ासि किरदारनि जी इजाज़त नाहे",
    searchPlaceholderText: "ॻोला लाइ टेक्स्ट दाख़िलु कयो",
    searchText: "खोजना",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "ज़राअत",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ए गवर्नन्स",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "तालीम",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "शक्ती",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "सिहत",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "समाजी भलाई",
        url: `https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "शबो",
    selectLanguageText: "चुंडियल ॿोली",
    twitterIcon: TwitterIcon,
    twitterLogoText: "विकासपीडया X (ख़ारजी लिंक)",
    urlAlternative: "",
    urlIdn: "https://xn--i1b8e2b2ah.xn--11by0av0at5becfj.xn--h2brj9c",
    urlLocal: "",
    urlSearch: "https://sd.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "20",
    vikaspediaLogoText: "विकासपीडया",
    vikaspediaOfferedIn: "विकास पीडया में पेश कयो व्यो",
    whatsappIcon: "",
    whatsappLogoText: "विकासपीडया WhatsApp (ख़ारजी लिंक)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "विकासपीडया YouTube (ख़ारजी लिंक)",
  },
  {
    languageShortName: "ta",
    aboutPortal1Text:
      "விகாஸ்பீடியா சமூக வளர்ச்சிக்கான டிஜிட்டல் வளங்களை வழங்கும் ஒரு பன்மொழி அறிவுப் பகிர்வு தளமாகும். ",
    aboutPortal2Text: "இந்திய அரசின் இம்முயற்சியை,",
    aboutPortal3Text: "செயல்படுத்தி வருகிறது.",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "விகாஸ்பீடியா iOS ஆப் (வெளிப்புற இணைப்பு)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (வெளிப்புற இணைப்பு)",
    cdacText: "உன்னத கணிப்பியல் வளர்ச்சி மையம் (C-DAC)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "டிஜிட்டல் இந்தியா (வெளிப்புற இணைப்பு)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "விகாஸ்பீடியா பேஸ்புக் (வெளிப்புற இணைப்பு)",
    hoverText: "Tamil",
    instagramIcon: InstagramIcon,
    instagramLogoText: "விகாஸ்பீடியா இன்ஸ்டாகிராம் (வெளிப்புற இணைப்பு)",
    label: "தமிழ்",
    lastmodified: "கடைசியாக மாற்றப்பட்டது",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "விகாஸ்பீடியா லிங்க்ட்இன் (வெளிப்புற இணைப்பு)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (வெளிப்புற இணைப்பு)",
    meityText: "மின்னணு மற்றும் தகவல் தொழில்நுட்ப அமைச்சகத்தின் (MeitY)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "விகாஸ்பீடியா ஆண்ட்ராய்டு ஆப் (வெளிப்புற இணைப்பு)",
    searchButton: "தேட இங்கே கிளிக் செய்யவும்",
    searchErrorText: "சிறப்பு எழுத்துக்கள் அனுமதி இல்லை",
    searchPlaceholderText: "தேட வார்த்தையை உள்ளிடவும்",
    searchText: "துறைகள்",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "வேளாண்மை",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "மின்னாட்சி",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "கல்வி",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "எரிசக்தி",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "ஆரோக்கியம்",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "சமூக நலம்",
        url: `https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "துறைகள்",
    selectLanguageText: "மொழியை தேர்ந்தெடுங்கள்",
    twitterIcon: TwitterIcon,
    twitterLogoText: "விகாஸ்பீடியா எக்ஸ் (வெளிப்புற இணைப்பு)",
    urlAlternative: "",
    urlIdn: "https://xn--clcu6av0at5becfj8m.xn--xkc2dl3a5ee0h",
    urlLocal: "",
    urlSearch: "https://ta.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "21",
    vikaspediaLogoText: "விகாஸ்பீடியா",
    vikaspediaOfferedIn: "விகாஸ்பீடியாவில் வழங்கப்படும் மொழிகள்",
    whatsappIcon: "",
    whatsappLogoText: "விகாஸ்பீடியா வாட்ஸ்அப் (வெளிப்புற இணைப்பு)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "விகாஸ்பீடியா யூடியூப் (வெளிப்புற இணைப்பு)",
  },
  {
    languageShortName: "te",
    aboutPortal1Text:
      "వికాస్పీడియా అనేది దేశవ్యాప్త బహుభాషా జ్ఞానాన్ని పంచుకునే వేదిక, ఇది సమాజ అభివృద్ధికి డిజిటల్ వనరులను అందిస్తుంది. ",
    aboutPortal2Text:
      "ఇది సెంటర్ ఫర్ డెవలప్‌మెంట్ ఆఫ్ అడ్వాన్స్‌డ్ కంప్యూటింగ్ (C-DAC) ద్వారా అమలు చేయబడిన భారత ప్రభుత్వ ఎలక్ట్రానిక్స్ మరియు ఇన్ఫర్మేషన్ టెక్నాలజీ మంత్రిత్వ శాఖ (MeitY) చొరవ.",
    aboutPortal3Text: "",
    aboutPortal4Text: "",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "వికాస్పీడియా iOS యాప్ (బాహ్య లింక్)",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (బాహ్య లింక్)",
    cdacText: "",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "డిజిటల్ ఇండియా (బాహ్య లింక్)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "వికాస్‌పీడియా ఫేస్‌బుక్ (బాహ్య లింక్)",
    hoverText: "Telugu",
    instagramIcon: InstagramIcon,
    instagramLogoText: "వికాస్పీడియా ఇన్‌స్టాగ్రామ్ (బాహ్య లింక్)",
    label: "తెలుగు",
    lastmodified: "చివరిగా సవరించబడింది",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "వికాస్పీడియా లింక్డ్‌ఇన్ (బాహ్య లింక్)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (బాహ్య లింక్)",
    meityText: "",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "వికాస్పీడియా ఆండ్రాయిడ్ యాప్ (బాహ్య లింక్)",
    searchButton: "శోధించడానికి ఇక్కడ క్లిక్ చేయండి",
    searchErrorText: "ప్రత్యేక అక్షరాలు అనుమతించబడవు",
    searchPlaceholderText: "శోధించడానికి వచనాన్ని నమోదు చేయండి",
    searchText: "శోధన/వెతకండి/అన్వేషణ",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "వ్యవసాయం",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ఇ-పాలన",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/e-governance`,
        value: "e-governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "విద్య",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "శక్తి",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "ఆరోగ్యం",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "సామాజిక సంక్షేమం",
        url: `https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "రంగాలు",
    selectLanguageText: "భాషను ఎంచుకోండి",
    twitterIcon: TwitterIcon,
    twitterLogoText: "వికాస్పీడియా ట్విట్టర్ (బాహ్య లింక్)",
    urlAlternative: "",
    urlIdn: "https://xn--zocy0av0at5becfj8m.xn--fpcrj9c3d",
    urlLocal: "",
    urlSearch: "https://te.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "22",
    vikaspediaLogoText: "వికాస్పీడియా",
    vikaspediaOfferedIn: "వికాస్పీడియాలో అందించబడిన భాషలు",
    whatsappIcon: "",
    whatsappLogoText: "వికాస్పీడియా వాట్సాప్ (బాహ్య లింక్)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "వికాస్పీడియా యూట్యూబ్ (బాహ్య లింక్)",
  },
  {
    languageShortName: "ur",

    aboutPortal1Text:
      " وکاس پیڈیا ایک ملک گیر کثیر لسانی نالج شیئرنگ پلیٹ فارم ہے جو معاشرے کی ترقی کے لیے ڈیجیٹل وسائل مہیا کرتا ہے۔",
    meityText: "وزارت برائے الیکٹرانکس اور انفارمیشن ٹیکنالوجی",
    cdacText: "سینٹر فار ڈیولپمنٹ آف ایڈوانسڈ کمپیوٹنگ  (سی - ڈی اے سی )",
    aboutPortal2Text: " حکومت ہند کی ایک پہل ہے جسے ",
    aboutPortal3Text: " نے نافذ کیا ہے۔",
    aboutPortal4Text: "مزید معلومات کے لئےدیکھیں۔",
    appstoreIcon: AppStoreIcon,
    appstoreLogoText: "وکاس پیڈیا ا ی او یس  ایپ (بیرونی لنک) ",
    cdacIcon: CdacIcon,
    cdacLogoText: "C-DAC (بیرونی لنک)",
    digitalIndiaIcon: DigitalIndiaIcon,
    digitalIndiaLogoText: "ڈیجیٹل انڈیا (بیرونی لنک)",
    facebookIcon: FacebookIcon,
    facebookLogoText: "وکاس پیڈیا فیس بک (بیرونی لنک)",
    hoverText: "Urdu",
    instagramIcon: InstagramIcon,
    instagramLogoText: "وکاس پیڈیا انسٹاگرام (بیرونی لنک)",
    label: "اردو",
    lastmodified: "آخری بار ترمیم کی گئی۔",
    lastmodifiedCdac: "C-DAC",
    linkedinIcon: LinkedInIcon,
    linkedinLogoText: "وکاس پیڈیا لنکڈ ان (بیرونی لنک)",
    meityIcon: MeityIcon,
    meityLogoText: "MeitY (بیرونی لنک)",
    playstoreIcon: PlayStoreIcon,
    playstoreLogoText: "وکاس پیڈیا اینڈرائیڈ ایپ (بیرونی لنک)",
    searchButton: "تلاش کرنے کے لیے یہاں کلک کریں۔",
    searchErrorText: "اسپیشل کراکٹرس کی اجازت نہیں ہے",
    searchPlaceholderText: "تلاش کرنے کے لیے متن درج کریں۔",
    searchText: "تلاش کریں۔",
    sectors: [
      {
        hoverText: "Agriculture",
        icon: AgricultureIcon,
        label: "زراعت",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/agriculture`,
        value: "agriculture",
      },

      {
        hoverText: "e-Governance",
        icon: AssuredWorkloadIcon,
        label: "ای گورننس",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/e-governance`,
        value: "e-Governance",
      },
      {
        hoverText: "Education",
        icon: SchoolIcon,
        label: "تعلیم",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/education`,
        value: "education",
      },
      {
        hoverText: "Energy",
        icon: WindPowerIcon,
        label: "توانائی",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/energy`,
        value: "energy",
      },
      {
        hoverText: "Health",
        icon: HealthAndSafetyIcon,
        label: "صحت",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/health`,
        value: "health",
      },

      {
        hoverText: "Social Welfare",
        icon: Diversity3Icon,
        label: "سماجی بہبود",
        url: `https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e/social-welfare`,
        value: "social-welfare",
      },
    ],
    sectorsText: "شعبے",
    selectLanguageText: "زبان منتخب کریں۔",
    twitterIcon: TwitterIcon,
    twitterLogoText: "وکاس پیڈیا ٹویٹر (بیرونی لنک)",
    urlAlternative: "",
    urlIdn: "https://xn----ymcb0c2ftokcznllb.xn--mgbbh1a71e",
    urlLocal: "",
    urlSearch: "https://ur.vikaspedia.in/populer-topics/",
    urlSubDomain: "",
    value: "23",
    vikaspediaLogoText: "وکاس پیڈیا",
    vikaspediaOfferedIn: "وکاس پیڈیا کی  پیشکش۔ ",
    whatsappIcon: "",
    whatsappLogoText: "وکاس پیڈیا واٹس ایپ (بیرونی لنک)",
    youtubeIcon: YouTubeIcon,
    youtubeLogoText: "وکاس پیڈیا یوٹیوب (بیرونی لنک)",
  },
];
