import { IDN_SITE_URL } from "./constant";
import SchoolIcon from "@mui/icons-material/School";
import HealthAndSafetyIcon from "@mui/icons-material/HealthAndSafety";
import Diversity3Icon from "@mui/icons-material/Diversity3";
import WindPowerIcon from "@mui/icons-material/WindPower";
import AssuredWorkloadIcon from "@mui/icons-material/AssuredWorkload";
import AgricultureIcon from "@mui/icons-material/Agriculture";
import ListAltIcon from "@mui/icons-material/ListAlt";
import LocationCityIcon from "@mui/icons-material/LocationCity";

export const keySkills = {
  as: [
    {
      label: "কৃষি",
      value: "কৃষি",
      url: `${IDN_SITE_URL.AS_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "কৃষি",
    },
    {
      label: "স্বাস্থ্য",
      value: "স্বাস্থ্য",
      url: `${IDN_SITE_URL.AS_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "স্বাস্থ্য",
    },
    {
      label: "শিক্ষা",
      value: "শিক্ষা",
      url: `${IDN_SITE_URL.AS_URL}/education`,
      icon: SchoolIcon,
      hoverText: "শিক্ষা",
    },
    {
      label: "সমাজ কল্যাণ",
      value: "সমাজ কল্যাণ",
      url: `${IDN_SITE_URL.AS_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "সমাজ কল্যাণ",
    },
    {
      label: "শক্তি",
      value: "শক্তি",
      url: `${IDN_SITE_URL.AS_URL}/rural-energy`,
      icon: WindPowerIcon,
      hoverText: "শক্তি",
    },
    {
      label: "ই-প্ৰশাসন",
      value: "ই-গভর্নেন্স",
      url: `${IDN_SITE_URL.AS_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ই-প্ৰশাসন",
    },
    {
      label: "আঁচনিসমূহ",
      value: "আঁচনিসমূহ",
      url: `${IDN_SITE_URL.AS_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "আঁচনিসমূহ",
    },
  ],
  bn: [
    {
      label: "কৃষি",
      value: "কৃষি",
      url: `${IDN_SITE_URL.BN_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "কৃষি",
    },
    {
      label: "স্বাস্থ্য",
      value: "স্বাস্থ্য",
      url: `${IDN_SITE_URL.BN_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "স্বাস্থ্য",
    },
    {
      label: "শিক্ষা",
      value: "শিক্ষা",
      url: `${IDN_SITE_URL.BN_URL}/education`,
      icon: SchoolIcon,
      hoverText: "শিক্ষা",
    },
    {
      label: "সমাজ কল্যাণ",
      value: "সমাজ কল্যাণ",
      url: `${IDN_SITE_URL.BN_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "সমাজ কল্যাণ",
    },
    {
      label: "শক্তি",
      value: "শক্তি",
      url: `${IDN_SITE_URL.BN_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "শক্তি",
    },
    {
      label: "ই-গভর্নেন্স",
      value: "ই-গভর্নেন্স",
      url: `${IDN_SITE_URL.BN_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ই-গভর্নেন্স",
    },
    {
      label: "পরিকল্পনা",
      value: "পরিকল্পনা",
      url: `${IDN_SITE_URL.BN_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "পরিকল্পনা",
    },
  ],
  brx: [
    {
      label: "आबाद मावनाय",
      value: "आबाद मावनाय",
      url: `${IDN_SITE_URL.BRX_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "आबाद मावनाय",
    },
    {
      label: "सावस्रि",
      value: "सावस्रि",
      url: `${IDN_SITE_URL.BRX_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "सावस्रि",
    },
    {
      label: "सोलोंथाइ",
      value: "सोलोंथाइ",
      url: `${IDN_SITE_URL.BRX_URL}/education`,
      icon: SchoolIcon,
      hoverText: "सोलोंथाइ",
    },
    {
      label: "समाजारि अनसुंथाइ",
      value: "समाजारि अनसुंथाइ",
      url: `${IDN_SITE_URL.BRX_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "समाजारि अनसुंथाइ",
    },
    {
      label: "गोहो",
      value: "गोहो",
      url: `${IDN_SITE_URL.BRX_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "गोहो",
    },
    {
      label: "मोब्लिबारि खुंथाय",
      value: "मोब्लिबारि खुंथाय",
      url: `${IDN_SITE_URL.BRX_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "मोब्लिबारि खुंथाय",
    },
    {
      label: "बिथांखि",
      value: "बिथांखि",
      url: `${IDN_SITE_URL.BRX_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "बिथांखि",
    },
  ],
  doi: [
    {
      label: "खेतीबाड़ी",
      value: "खेतीबाड़ी",
      url: `${IDN_SITE_URL.DOI_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "खेतीबाड़ी",
    },
    {
      label: "सेहत",
      value: "सेहत",
      url: `${IDN_SITE_URL.DOI_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "सेहत",
    },
    {
      label: "पढ़ाई",
      value: "पढ़ाई",
      url: `${IDN_SITE_URL.DOI_URL}/education`,
      icon: SchoolIcon,
      hoverText: "पढ़ाई",
    },
    {
      label: "समाजिक भलाई",
      value: "समाजिक भलाई",
      url: `${IDN_SITE_URL.DOI_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "समाजिक भलाई",
    },
    {
      label: "उर्जा",
      value: "उर्जा",
      url: `${IDN_SITE_URL.DOI_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "उर्जा",
    },
    {
      label: "ई –गवर्नेंस",
      value: "ई –गवर्नेंस",
      url: `${IDN_SITE_URL.DOI_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ई –गवर्नेंस",
    },
    {
      label: "योजनाएं",
      value: "schemes",
      url: `${IDN_SITE_URL.DOI_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "Schemes",
    },
  ],
  en: [
    {
      label: "Agriculture",
      value: "agriculture",
      url: `${IDN_SITE_URL.EN_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "Agriculture",
    },
    {
      label: "Health",
      value: "health",
      url: `${IDN_SITE_URL.EN_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "Health",
    },
    {
      label: "Education",
      value: "education",
      url: `${IDN_SITE_URL.EN_URL}/education`,
      icon: SchoolIcon,
      hoverText: "Education",
    },
    {
      label: "Social Welfare",
      value: "social-welfare",
      url: `${IDN_SITE_URL.EN_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "Social Welfare",
    },
    {
      label: "Energy",
      value: "energy",
      url: `${IDN_SITE_URL.EN_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "Energy",
    },
    {
      label: "E-Governance",
      value: "e-governance",
      url: `${IDN_SITE_URL.EN_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "E-Governance",
    },
    {
      label: "Schemes",
      value: "schemes",
      url: `${IDN_SITE_URL.EN_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "Schemes",
    },
    {
      label: "Aspirational District",
      value: "aspirational",
      url: `${IDN_SITE_URL.EN_URL}/aspirational`,
      icon: LocationCityIcon,
      hoverText: "Aspirational District",
    },
  ],
  gu: [
    {
      label: "ખેતીવાડી",
      value: "ખેતીવાડી",
      url: `${IDN_SITE_URL.GU_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "ખેતીવાડી",
    },
    {
      label: "આરોગ્ય",
      value: "આરોગ્ય",
      url: `${IDN_SITE_URL.GU_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "આરોગ્ય",
    },
    {
      label: "શિક્ષણ",
      value: "શિક્ષણ",
      url: `${IDN_SITE_URL.GU_URL}/education`,
      icon: SchoolIcon,
      hoverText: "શિક્ષણ",
    },
    {
      label: "સામાજ ક્લ્યાણ",
      value: "સામાજ ક્લ્યાણ",
      url: `${IDN_SITE_URL.GU_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "સામાજ ક્લ્યાણ",
    },
    {
      label: "ઊર્જા",
      value: "ઊર્જા",
      url: `${IDN_SITE_URL.GU_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "ઊર્જા",
    },
    {
      label: "ઈ-શાસન",
      value: "ઈ-શાસન",
      url: `${IDN_SITE_URL.GU_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ઈ-શાસન",
    },
    {
      label: "યોજનાઓ",
      value: "યોજનાઓ",
      url: `${IDN_SITE_URL.GU_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "યોજનાઓ",
    },
  ],
  hi: [
    {
      label: "कृषि",
      value: "कृषि",
      url: `${IDN_SITE_URL.HI_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "कृषि",
    },
    {
      label: "स्वास्थ्य",
      value: "स्वास्थ्य",
      url: `${IDN_SITE_URL.HI_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "स्वास्थ्य",
    },
    {
      label: "शिक्षा",
      value: "शिक्षा",
      url: `${IDN_SITE_URL.HI_URL}/education`,
      icon: SchoolIcon,
      hoverText: "शिक्षा",
    },
    {
      label: "समाज कल्याण",
      value: "समाज कल्याण",
      url: `${IDN_SITE_URL.HI_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "समाज कल्याण",
    },
    {
      label: "ऊर्जा",
      value: "ऊर्जा",
      url: `${IDN_SITE_URL.HI_URL}/rural-energy`,
      icon: WindPowerIcon,
      hoverText: "ऊर्जा",
    },
    {
      label: "ई-शासन",
      value: "ई-शासन",
      url: `${IDN_SITE_URL.HI_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ई-शासन",
    },
    {
      label: "योजना",
      value: "योजना",
      url: `${IDN_SITE_URL.HI_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "योजना",
    },
    {
      label: "आकांक्षात्मक जिला",
      value: "आकांक्षात्मक जिला",
      url: `${IDN_SITE_URL.HI_URL}/aspirational`,
      icon: LocationCityIcon,
      hoverText: "आकांक्षात्मक जिला",
    },
  ],
  kn: [
    {
      label: "ಕೃಷಿ",
      value: "ಕೃಷಿ",
      url: `${IDN_SITE_URL.KN_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "ಕೃಷಿ",
    },
    {
      label: "ಆರೋಗ್ಯ",
      value: "ಆರೋಗ್ಯ",
      url: `${IDN_SITE_URL.KN_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "ಆರೋಗ್ಯ",
    },
    {
      label: "ಶಿಕ್ಷಣ",
      value: "ಶಿಕ್ಷಣ",
      url: `${IDN_SITE_URL.KN_URL}/education`,
      icon: SchoolIcon,
      hoverText: "ಶಿಕ್ಷಣ",
    },
    {
      label: "ಸಮಾಜ ಕಲ್ಯಾಣ",
      value: "ಸಮಾಜ ಕಲ್ಯಾಣ",
      url: `${IDN_SITE_URL.KN_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "ಸಮಾಜ ಕಲ್ಯಾಣ",
    },
    {
      label: "ಇಂಧನ",
      value: "ಇಂಧನ",
      url: `${IDN_SITE_URL.KN_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "ಇಂಧನ",
    },
    {
      label: "ಇ. ಆಡಳಿತ",
      value: "ಇ. ಆಡಳಿತ",
      url: `${IDN_SITE_URL.KN_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ಇ. ಆಡಳಿತ",
    },
    {
      label: "ಯೋಜನೆಗಳು",
      value: "ಯೋಜನೆಗಳು",
      url: `${IDN_SITE_URL.KN_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "ಯೋಜನೆಗಳು",
    },
  ],
  ks: [
    {
      label: "زِراتھ",
      value: "زِراتھ",
      url: `${IDN_SITE_URL.KS_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "زِراتھ",
    },
    {
      label: "صیحَتھ",
      value: "صیحَتھ",
      url: `${IDN_SITE_URL.KS_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "صیحَتھ",
    },
    {
      label: "تٱلیٖم",
      value: "تٱلیٖم",
      url: `${IDN_SITE_URL.KS_URL}/education`,
      icon: SchoolIcon,
      hoverText: "تٱلیٖم",
    },
    {
      label: "سمٱجی بہبوٗدی",
      value: "سمٱجی بہبوٗدی",
      url: `${IDN_SITE_URL.KS_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "سمٱجی بہبوٗدی",
    },
    {
      label: "گٱمی تَوانٱیی",
      value: "گٱمی تَوانٱیی",
      url: `${IDN_SITE_URL.KS_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "گٱمی تَوانٱیی",
    },
    {
      label: "ای ۔ گَوَرنَنٕس",
      value: "ای ۔ گَوَرنَنٕس",
      url: `${IDN_SITE_URL.KS_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ای ۔ گَوَرنَنٕس",
    },
    {
      label: "Schemes",
      value: "Schemes",
      url: `${IDN_SITE_URL.KS_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "Schemes",
    },
  ],
  kok: [
    {
      label: "कृशी",
      value: "कृशी",
      url: `${IDN_SITE_URL.KOK_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "कृशी",
    },
    {
      label: "भलायकी",
      value: "भलायकी",
      url: `${IDN_SITE_URL.KOK_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "भलायकी",
    },
    {
      label: "शिक्षण",
      value: "शिक्षण",
      url: `${IDN_SITE_URL.KOK_URL}/education`,
      icon: SchoolIcon,
      hoverText: "शिक्षण",
    },
    {
      label: "समाज कल्याण",
      value: "समाज कल्याण",
      url: `${IDN_SITE_URL.KOK_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "समाज कल्याण",
    },
    {
      label: "उर्जा",
      value: "उर्जा",
      url: `${IDN_SITE_URL.KOK_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "उर्जा",
    },
    {
      label: "ई-गर्वनन्स",
      value: "ई-गर्वनन्स",
      url: `${IDN_SITE_URL.KOK_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ई-गर्वनन्स",
    },
    {
      label: "येवजण्यो",
      value: "येवजण्यो",
      url: `${IDN_SITE_URL.KOK_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "येवजण्यो",
    },
  ],
  mai: [
    {
      label: "खेती-बाड़ी",
      value: "खेती-बाड़ी",
      url: `${IDN_SITE_URL.MAI_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "खेती-बाड़ी",
    },
    {
      label: "स्वस्थ",
      value: "स्वस्थ",
      url: `${IDN_SITE_URL.MAI_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "स्वस्थ",
    },
    {
      label: "शिक्षा",
      value: "शिक्षा",
      url: `${IDN_SITE_URL.MAI_URL}/education`,
      icon: SchoolIcon,
      hoverText: "शिक्षा",
    },
    {
      label: "सामाजिक कल्याण",
      value: "सामाजिक कल्याण",
      url: `${IDN_SITE_URL.MAI_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "सामाजिक कल्याण",
    },
    {
      label: "ऊर्जा",
      value: "ऊर्जा",
      url: `${IDN_SITE_URL.MAI_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "ऊर्जा",
    },
    {
      label: "इ-गवर्नेंस",
      value: "इ-गवर्नेंस",
      url: `${IDN_SITE_URL.MAI_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "इ-गवर्नेंस",
    },
    {
      label: "योजना",
      value: "योजना",
      url: `${IDN_SITE_URL.MAI_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "योजना",
    },
  ],
  ml: [
    {
      label: "കൃഷി",
      value: "കൃഷി",
      url: `${IDN_SITE_URL.ML_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "കൃഷി",
    },
    {
      label: "ആരോഗ്യം",
      value: "ആരോഗ്യം",
      url: `${IDN_SITE_URL.ML_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "ആരോഗ്യം",
    },
    {
      label: "വിദ്യാഭ്യാസം",
      value: "വിദ്യാഭ്യാസം",
      url: `${IDN_SITE_URL.ML_URL}/education`,
      icon: SchoolIcon,
      hoverText: "വിദ്യാഭ്യാസം",
    },
    {
      label: "സാമൂഹ്യക്ഷേമ",
      value: "സാമൂഹ്യക്ഷേമ",
      url: `${IDN_SITE_URL.ML_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "സാമൂഹ്യക്ഷേമ",
    },
    {
      label: "ഊർജം",
      value: "ഊർജം",
      url: `${IDN_SITE_URL.ML_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "ഊർജം",
    },
    {
      label: "ഇ-ഭരണം",
      value: "ഇ-ഭരണം",
      url: `${IDN_SITE_URL.ML_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ഇ-ഭരണം",
    },
    {
      label: "സ്‌കീം",
      value: "സ്‌കീം",
      url: `${IDN_SITE_URL.ML_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "സ്‌കീം",
    },
  ],
  mni: [
    {
      label: "লৌউ-শীংউ",
      value: "লৌউ-শীংউ",
      url: `${IDN_SITE_URL.MNI_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "লৌউ-শীংউ",
    },
    {
      label: "হকশেল",
      value: "হকশেল",
      url: `${IDN_SITE_URL.MNI_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "হকশেল",
    },
    {
      label: "মহৈ-মশিং তম্বা",
      value: "মহৈ-মশিং তম্বা",
      url: `${IDN_SITE_URL.MNI_URL}/education`,
      icon: SchoolIcon,
      hoverText: "মহৈ-মশিং তম্বা",
    },
    {
      label: "মীয়ামগী য়াইফ-থৌরাং",
      value: "মীয়ামগী য়াইফ-থৌরাং",
      url: `${IDN_SITE_URL.MNI_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "মীয়ামগী য়াইফ-থৌরাং",
    },
    {
      label: "এনর্জি",
      value: "এনর্জি",
      url: `${IDN_SITE_URL.MNI_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "এনর্জি",
    },
    {
      label: "ই-গবর্ণান্স",
      value: "ই-গবর্ণান্স",
      url: `${IDN_SITE_URL.MNI_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ই-গবর্ণান্স",
    },
    {
      label: "স্কিমশিং",
      value: "স্কিমশিং",
      url: `${IDN_SITE_URL.MNI_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "স্কিমশিং",
    },
  ],
  mr: [
    {
      label: "शेती",
      value: "शेती",
      url: `${IDN_SITE_URL.MR_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "कृषि",
    },
    {
      label: "आरोग्य",
      value: "आरोग्य",
      url: `${IDN_SITE_URL.MR_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "आरोग्य",
    },
    {
      label: "शिक्षण",
      value: "शिक्षण",
      url: `${IDN_SITE_URL.MR_URL}/education`,
      icon: SchoolIcon,
      hoverText: "शिक्षण",
    },
    {
      label: "समाज कल्याण",
      value: "समाज कल्याण",
      url: `${IDN_SITE_URL.MR_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "समाज कल्याण",
    },
    {
      label: "ऊर्जा",
      value: "ऊर्जा",
      url: `${IDN_SITE_URL.MR_URL}/rural-energy`,
      icon: WindPowerIcon,
      hoverText: "ऊर्जा",
    },
    {
      label: "ई-गव्हर्नन्स",
      value: "ई-गव्हर्नन्स",
      url: `${IDN_SITE_URL.MR_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ई-गव्हर्नन्स",
    },
    {
      label: "योजना",
      value: "योजना",
      url: `${IDN_SITE_URL.MR_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "योजना",
    },
  ],
  ne: [
    {
      label: "कृषि",
      value: "कृषि",
      url: `${IDN_SITE_URL.NE_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "कृषि",
    },
    {
      label: "स्वास्थ्य",
      value: "स्वास्थ्य",
      url: `${IDN_SITE_URL.NE_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "स्वास्थ्य",
    },
    {
      label: "शिक्षा",
      value: "शिक्षा",
      url: `${IDN_SITE_URL.NE_URL}/education`,
      icon: SchoolIcon,
      hoverText: "शिक्षा",
    },
    {
      label: "समाज कल्याण",
      value: "समाज कल्याण",
      url: `${IDN_SITE_URL.NE_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "समाज कल्याण",
    },
    {
      label: "ऊर्जा",
      value: "ऊर्जा",
      url: `${IDN_SITE_URL.NE_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "ऊर्जा",
    },
    {
      label: "इ-शासन",
      value: "इ-शासन",
      url: `${IDN_SITE_URL.NE_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "इ-शासन",
    },
    {
      label: "योजनाहरू",
      value: "योजनाहरू",
      url: `${IDN_SITE_URL.NE_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "योजनाहरू",
    },
  ],
  or: [
    {
      label: "କୃଷି",
      value: "କୃଷି",
      url: `${IDN_SITE_URL.OR_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "କୃଷି",
    },
    {
      label: "ସ୍ଵାସ୍ଥ୍ୟ",
      value: "ସ୍ଵାସ୍ଥ୍ୟ",
      url: `${IDN_SITE_URL.OR_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "ସ୍ଵାସ୍ଥ୍ୟ",
    },
    {
      label: "ଶିକ୍ଷା",
      value: "ଶିକ୍ଷା",
      url: `${IDN_SITE_URL.OR_URL}/education`,
      icon: SchoolIcon,
      hoverText: "ଶିକ୍ଷା",
    },
    {
      label: "ସମାଜ କଲ୍ୟାଣ",
      value: "ସମାଜ କଲ୍ୟାଣ",
      url: `${IDN_SITE_URL.OR_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "ସମାଜ କଲ୍ୟାଣ",
    },
    {
      label: "ଶକ୍ତି",
      value: "ଶକ୍ତି",
      url: `${IDN_SITE_URL.OR_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "ଶକ୍ତି",
    },
    {
      label: "ଇ-ଗଭର୍ଣ୍ଣ।ନ୍ସ",
      value: "ଇ-ଗଭର୍ଣ୍ଣ।ନ୍ସ",
      url: `${IDN_SITE_URL.OR_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ଇ-ଗଭର୍ଣ୍ଣ।ନ୍ସ",
    },
    {
      label: "ଯୋଜନାଗୁଡିକ",
      value: "ଯୋଜନାଗୁଡିକ",
      url: `${IDN_SITE_URL.OR_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "ଯୋଜନାଗୁଡିକ",
    },
  ],
  pa: [
    {
      label: "ਖੇਤੀ ਬਾੜੀ",
      value: "ਖੇਤੀ ਬਾੜੀ",
      url: `${IDN_SITE_URL.PA_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "ਖੇਤੀ ਬਾੜੀ",
    },
    {
      label: "ਸਿਹਤ",
      value: "ਸਿਹਤ",
      url: `${IDN_SITE_URL.PA_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "ਸਿਹਤ",
    },
    {
      label: "ਸਿੱਖਿਆ",
      value: "ਸਿੱਖਿਆ",
      url: `${IDN_SITE_URL.PA_URL}/education`,
      icon: SchoolIcon,
      hoverText: "ਸਿੱਖਿਆ",
    },
    {
      label: "ਸਮਾਜਿਕ ਭਲਾਈ",
      value: "ਸਮਾਜਿਕ ਭਲਾਈ",
      url: `${IDN_SITE_URL.PA_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "ਸਮਾਜਿਕ ਭਲਾਈ",
    },
    {
      label: ".ਰਜਾ",
      value: ".ਰਜਾ",
      url: `${IDN_SITE_URL.PA_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: ".ਰਜਾ",
    },
    {
      label: "ਈ-ਗਵਰਨੈਂਸ",
      value: "ਈ-ਗਵਰਨੈਂਸ",
      url: `${IDN_SITE_URL.PA_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ਈ-ਗਵਰਨੈਂਸ",
    },
    {
      label: "ਸਕੀਮਾਂ",
      value: "ਸਕੀਮਾਂ",
      url: `${IDN_SITE_URL.PA_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "ਸਕੀਮਾਂ",
    },
  ],
  sa: [
    {
      label: "कृषिः",
      value: "कृषिः",
      url: `${IDN_SITE_URL.SA_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "कृषिः",
    },
    {
      label: "स्वास्थ्यम्",
      value: "स्वास्थ्यम्",
      url: `${IDN_SITE_URL.SA_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "स्वास्थ्यम्",
    },
    {
      label: "शिक्षा",
      value: "शिक्षा",
      url: `${IDN_SITE_URL.SA_URL}/education`,
      icon: SchoolIcon,
      hoverText: "शिक्षा",
    },
    {
      label: "सामाजकल्याणम्",
      value: "सामाजकल्याणम्",
      url: `${IDN_SITE_URL.SA_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "सामाजकल्याणम्",
    },
    {
      label: "ऊर्जा",
      value: "ऊर्जा",
      url: `${IDN_SITE_URL.SA_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "ऊर्जा",
    },
    {
      label: "ई-शासनम्",
      value: "ई-शासनम्",
      url: `${IDN_SITE_URL.SA_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ई-शासनम्",
    },
    {
      label: "योजनाः",
      value: "योजनाः",
      url: `${IDN_SITE_URL.SA_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "योजनाः",
    },
  ],
  sat: [
    {
      label: "ᱪᱟᱥᱵᱟᱥ",
      value: "ᱪᱟᱥᱵᱟᱥ",
      url: `${IDN_SITE_URL.SAT_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "ᱪᱟᱥᱵᱟᱥ",
    },
    {
      label: "ᱱᱤᱨᱚᱯᱚᱱ",
      value: "ᱱᱤᱨᱚᱯᱚᱱ",
      url: `${IDN_SITE_URL.SAT_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "ᱱᱤᱨᱚᱯᱚᱱ",
    },
    {
      label: "ᱥᱤᱠᱷᱱᱟᱛ",
      value: "ᱥᱤᱠᱷᱱᱟᱛ",
      url: `${IDN_SITE_URL.SAT_URL}/education`,
      icon: SchoolIcon,
      hoverText: "ᱥᱤᱠᱷᱱᱟᱛ",
    },
    {
      label: "ᱥᱟᱸᱣᱟ ᱵᱷᱟᱞᱟᱤ",
      value: "ᱥᱟᱸᱣᱟ ᱵᱷᱟᱞᱟᱤ",
      url: `${IDN_SITE_URL.SAT_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "ᱥᱟᱸᱣᱟ ᱵᱷᱟᱞᱟᱤ",
    },
    {
      label: "ᱛᱟᱯᱤᱥ",
      value: "ᱛᱟᱯᱤᱥ",
      url: `${IDN_SITE_URL.SAT_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "ᱛᱟᱯᱤᱥ",
    },
    {
      label: "ᱤ-ᱜᱟᱵᱨᱱᱮᱱᱥ",
      value: "ᱤ-ᱜᱟᱵᱨᱱᱮᱱᱥ",
      url: `${IDN_SITE_URL.SAT_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ᱤ-ᱜᱟᱵᱨᱱᱮᱱᱥ",
    },
    {
      label: "ᱯᱚᱱᱛᱷᱟ ᱠᱚ",
      value: "ᱯᱚᱱᱛᱷᱟ ᱠᱚ",
      url: `${IDN_SITE_URL.SAT_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "ᱯᱚᱱᱛᱷᱟ ᱠᱚ",
    },
  ],
  sd: [
    {
      label: "ज़राअत",
      value: "ज़राअत",
      url: `${IDN_SITE_URL.SD_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "ज़राअत",
    },
    {
      label: "सिहत",
      value: "सिहत",
      url: `${IDN_SITE_URL.SD_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "सिहत",
    },
    {
      label: "तालीम",
      value: "तालीम",
      url: `${IDN_SITE_URL.SD_URL}/education`,
      icon: SchoolIcon,
      hoverText: "तालीम",
    },
    {
      label: "समाजी भलाई",
      value: "समाजी भलाई",
      url: `${IDN_SITE_URL.SD_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "समाजी भलाई",
    },
    {
      label: "शक्ती",
      value: "शक्ती",
      url: `${IDN_SITE_URL.SD_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "शक्ती",
    },
    {
      label: "ई-गवर्नन्स",
      value: "ई-गवर्नन्स",
      url: `${IDN_SITE_URL.SD_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ई-गवर्नन्स",
    },
    {
      label: "योजनाऊं",
      value: "योजनाऊं",
      url: `${IDN_SITE_URL.SD_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "योजनाऊं",
    },
  ],
  ta: [
    {
      label: "விவசாயம்",
      value: "விவசாயம்",
      url: `${IDN_SITE_URL.TA_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "விவசாயம்",
    },
    {
      label: "ஆரோக்கியம்",
      value: "ஆரோக்கியம்",
      url: `${IDN_SITE_URL.TA_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "ஆரோக்கியம்",
    },
    {
      label: "கல்வி",
      value: "கல்வி",
      url: `${IDN_SITE_URL.TA_URL}/education`,
      icon: SchoolIcon,
      hoverText: "கல்வி",
    },
    {
      label: "சமூக நல",
      value: "சமூக நல",
      url: `${IDN_SITE_URL.TA_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "சமூக நல",
    },
    {
      label: "எரிசக்தி",
      value: "எரிசக்தி",
      url: `${IDN_SITE_URL.TA_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "எரிசக்தி",
    },
    {
      label: "மின்னாட்சி",
      value: "மின்னாட்சி",
      url: `${IDN_SITE_URL.TA_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "மின்னாட்சி",
    },
    {
      label: "திட்டங்கள்",
      value: "திட்டங்கள்",
      url: `${IDN_SITE_URL.TA_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "திட்டங்கள்",
    },
  ],
  te: [
    {
      label: "వ్యవసాయం",
      value: "వ్యవసాయం",
      url: `${IDN_SITE_URL.TE_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "వ్యవసాయం",
    },
    {
      label: "ఆరోగ్యం",
      value: "ఆరోగ్యం",
      url: `${IDN_SITE_URL.TE_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "ఆరోగ్యం",
    },
    {
      label: "చదువు",
      value: "చదువు",
      url: `${IDN_SITE_URL.TE_URL}/education`,
      icon: SchoolIcon,
      hoverText: "చదువు",
    },
    {
      label: "సామాజిక సంక్షేమం",
      value: "సామాజిక సంక్షేమం",
      url: `${IDN_SITE_URL.TE_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "సామాజిక సంక్షేమం",
    },
    {
      label: "శక్తి",
      value: "శక్తి",
      url: `${IDN_SITE_URL.TE_URL}/rural-energy`,
      icon: WindPowerIcon,
      hoverText: "శక్తి",
    },
    {
      label: "ఇ-గవర్నెన్స్",
      value: "ఇ-గవర్నెన్స్",
      url: `${IDN_SITE_URL.TE_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ఇ-గవర్నెన్స్",
    },
    {
      label: "పథకాలు",
      value: "పథకాలు",
      url: `${IDN_SITE_URL.TE_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "పథకాలు",
    },
  ],
  ur: [
    {
      label: "زراعت",
      value: "زراعت",
      url: `${IDN_SITE_URL.UR_URL}/agriculture`,
      icon: AgricultureIcon,
      hoverText: "زراعت",
    },
    {
      label: "صحت",
      value: "صحت",
      url: `${IDN_SITE_URL.UR_URL}/health`,
      icon: HealthAndSafetyIcon,
      hoverText: "صحت",
    },
    {
      label: "تعلیم",
      value: "تعلیم",
      url: `${IDN_SITE_URL.UR_URL}/education`,
      icon: SchoolIcon,
      hoverText: "تعلیم",
    },
    {
      label: "سماجی بہبود",
      value: "سماجی بہبود",
      url: `${IDN_SITE_URL.UR_URL}/social-welfare`,
      icon: Diversity3Icon,
      hoverText: "سماجی بہبود",
    },
    {
      label: "دیہی توانائی",
      value: "دیہی توانائی",
      url: `${IDN_SITE_URL.UR_URL}/energy`,
      icon: WindPowerIcon,
      hoverText: "دیہی توانائی",
    },
    {
      label: "ای  گورننس",
      value: "ای  گورننس",
      url: `${IDN_SITE_URL.UR_URL}/e-governance`,
      icon: AssuredWorkloadIcon,
      hoverText: "ای  گورننس",
    },
    {
      label: "سکیمیں",
      value: "سکیمیں",
      url: `${IDN_SITE_URL.UR_URL}/schemes`,
      icon: ListAltIcon,
      hoverText: "سکیمیں",
    },
  ],
};
